### ISSUE TITLE
Compilation error on Debian testing (g++-4.9.2)

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#1]
/home/olece/test/jucipp/juci/source.cc: In constructor 'Source::Model::Model(const Source::Config&)':
/home/olece/test/jucipp/juci/source.cc:105:17: error: no matching function for call to 'clang::TranslationUnit::TranslationUnit()'
   config_(config) {
                 ^
/home/olece/test/jucipp/juci/source.cc:105:17: note: candidates are:
In file included from /usr/local/lib/libclangmm/include/clangmm.h:3:0,
                 from /home/olece/test/jucipp/juci/source.h:7,
                 from /home/olece/test/jucipp/juci/source.cc:1:
/usr/local/lib/libclangmm/include/TranslationUnit.h:27:5: note: clang::TranslationUnit::TranslationUnit(clang::Index*, const string&)
     TranslationUnit(Index *index,
     ^
/usr/local/lib/libclangmm/include/TranslationUnit.h:27:5: note:   candidate expects 2 arguments, 0 provided
/usr/local/lib/libclangmm/include/TranslationUnit.h:23:5: note: clang::TranslationUnit::TranslationUnit(clang::Index*, const string&, const std::vector<const char*>&, const std::map<std::basic_string<char>, std::basic_string<char> >&)
     TranslationUnit(Index *index,
     ^
/usr/local/lib/libclangmm/include/TranslationUnit.h:23:5: note:   candidate expects 4 arguments, 0 provided
/usr/local/lib/libclangmm/include/TranslationUnit.h:20:5: note: clang::TranslationUnit::TranslationUnit(clang::Index*, const string&, const std::vector<const char*>&)
     TranslationUnit(Index *index,
     ^
/usr/local/lib/libclangmm/include/TranslationUnit.h:20:5: note:   candidate expects 3 arguments, 0 provided
/usr/local/lib/libclangmm/include/TranslationUnit.h:18:9: note: constexpr clang::TranslationUnit::TranslationUnit(const clang::TranslationUnit&)
   class TranslationUnit {
         ^
/usr/local/lib/libclangmm/include/TranslationUnit.h:18:9: note:   candidate expects 1 argument, 0 provided
CMakeFiles/juci.dir/build.make:123: recipe for target 'CMakeFiles/juci.dir/source.cc.o' failed
make[2]: *** [CMakeFiles/juci.dir/source.cc.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/juci.dir/all' failed
make[1]: *** [CMakeFiles/juci.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zalox** [comment]
This issue is solved by pulling the branch linked in the dependencies. (the libclangmm has a specific juci branch)

**Comment by eidheim** [comment]
Thank you, compilation works now.
