### ISSUE TITLE
yotta integration

### ISSUE THREAD

**Issue by autopulated** [cppit/jucipp#119]
What do you think about integrating [yotta](https://github.com/ARMmbed/yotta)?

It's a module system for C & C++, with build-system based around CMake.

**Comment by zalox** [comment]
I guess this should be possible to implement as a plugin with our plugin system arriving in one of the next releases.

**Comment by autopulated** [comment]
:+1: Sounds cool – just wanted to point it out to you as seems like it might be a really good fit.

**Comment by eidheim** [comment]
See also #97

**Comment by eidheim** [comment]
Closing this as it is somewhat a duplicate of #97, added your link there instead:)

**Comment by autopulated** [comment]
:thumbsup:
