### ISSUE TITLE
Missing declaration of clang_CompilationDatabase_getAllCompileCommands

### ISSUE THREAD

**Issue by pgoodman** [cppit/jucipp#120]
This function declaration is missing in the headers from my aptitude-installed libclang package(s). Is this a llvm 3.7.0 thing?

**Comment by eidheim** [comment]
What platform and libclang version do you use?

**Comment by pgoodman** [comment]
Ubuntu 14.04. I seem to have all of lib/clang/llvm 3.4, 3.5, and 3.6 installed.

**Comment by eidheim** [comment]
Best would be to use 3.6. Have note tested with 3.4, and that might be the issue. If you can, uninstall 3.4 and 3.5, rm CMakeCache.txt and CMakeFiles from your jucipp directory, and run cmake and make again.

**Comment by eidheim** [comment]
@pgoodman can we close this issue?

**Comment by pgoodman** [comment]
Yes. I managed to install it by manually setting `CXXFLAGS` with `-isystem` to point to the correct directory.
