### ISSUE TITLE
Add CMake builddir option

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#121]
Never thought about it before, since I always ignore the CMake-generated files using .gitignore, but there are probably some cmake option that make this doable. Will look into this soon, and most likely add this option in preferences.

**Comment by zalox** [comment]
I think we already support this. CLion for instance utilizes cmakes command line options to do this. We could add an option simplifying this interface.

**Comment by eidheim** [comment]
Might be, but the `.` when running `cmake .` is hardcoded, and then there is the problem of finding a compile_commands.json file if the build is in a different directory. But again, you might be correct that it is all a matter of editing cmake_command in preferences.

**Comment by zalox** [comment]
We should move the dot to the config anyways.

**Comment by eidheim** [comment]
Very true

**Comment by zalox** [comment]
```php
"project": {
   "build": {
    "<command>" : [
        "command-line-parameters",
    ],
    "target":""
   },
   "make_command": "make"
}
```
Something like this. We could list options that are frequently used.

**Comment by eidheim** [comment]
See here: http://stackoverflow.com/questions/7724569/debug-vs-release-in-cmake

**Comment by eidheim** [comment]
So the options would then be cmake_command, release_folder and debug_folder maybe, but this is also dependent on how we solve #53.

**Comment by zalox** [comment]
Relevant http://stackoverflow.com/a/90054

**Comment by bbenoist** [comment]
Hi,

I'm taking some personal time to comment on this issue because I am afraid too much assumptions are made here.

As I understood it, your discussions are currently converging to an overlay which would end-up not being compatible with some common CMake use-cases.

As I believe your approach on CMake is not 100% correct, here are some facts about the tool which I find interesting to note:
* CMake build directories can be multiple and placed anywhere. There is no convention about specific directory locations and there should not be.
* CMake source directory is not aware of its build directories. Only the inverse is true.
* CMake build modes (i.e. [`CMAKE_BUILD_TYPE`](https://cmake.org/cmake/help/v3.4/variable/CMAKE_BUILD_TYPE.html)) are not limited to Release and Debug:
      * By default, the RelWithDebInfo and MinSizeRel are also available.
      * You can [define custom build modes](https://cmake.org/Wiki/CMake_FAQ#How_can_I_extend_the_build_modes_with_a_custom_made_one_.3F).

As I prefer complains accompanied with solutions, here is my POV on the subject:
* Either:
    * Take the "QtCreator approach" and only let 1 build directory be chosen
    * Make multiple build directories definable.
* Do not make any assumption which is only based on both CMAKE_BUILD_TYPE and VS default build configurations.
* Use `cmake --build <dir>` instead of forcing a specific generator to be used.
* Whenever possible, rely on the CMake cache to retrieve information.
* Support the selective build of CMake targets.

Let me know if you want more arguments on a specific point and I will try to explain myself more...

Also, [my CMake-support contribution](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/CMake.fs) on the [FAKE (F# Make)](http://fsharp.github.io/FAKE/) project might also help you :wink:

**Comment by bbenoist** [comment]
> CMake build directories can be multiple and placed anywhere. There is no convention about specific directory locations and there should not be.

A comment on /r/cpp (11 upvotes) about the actual jucipp CMake build directory support:

> [I won't open this sofware again until it stops creating all the CMake junk in my src instead of a directory I choose.](https://www.reddit.com/r/cpp/comments/3wsej0/juci_100_released_a_new_lightweight_platform/cxyqt4i)

**Comment by eidheim** [comment]
I'll probably fix this Tomorrow as well if there are no issues with libclang on this. Where do you guys want the build directory as default? .release/release/Release/.build/build/Build under the project dir? I do not know what is most common, however, I think its a bad idea to place this directory in the ~ directory, like Qt Creator does it (for instance ~/build-project_name....).

**Comment by eidheim** [comment]
Maybe .build/release? Then we add .build/debug when we get debug support?

**Comment by eidheim** [comment]
Or .juci-build/release?

**Comment by eidheim** [comment]
Or wait, I guess the cmake variable CMAKE_BUILD_TYPE should decide the build type. Most common seems to be Release and Debug. Have to check what this variable contains by default.

**Comment by danielotero** [comment]
I usually have the build directory at the same level as the source dir and I think this is the default behavior of QtCreator.
And the name of the build directory may have the CMAKE_BUILD_TYPE embedded, so you can have different build directories for Debug or Release builds.
Also, I think the CMAKE_BUILD_TYPE has to be defined manually, but maybe is a good practice to guide new users to define it in the first build.

**Comment by bbenoist** [comment]
> I'll probably fix this Tomorrow if there are no issues with libclang on this. Where do you guys want the build directory as default? .release/release/Release/.build/build/Build under the project dir? I do not know what is most common, however, I think its a bad idea to place this directory in the .. directory, like Qt Creator does it (for instance ../build-project_name....). 
> Edit: Qt Creator places the build directory in ../build...

My personal choice goes over `./build`. When I have to build multiple variants from the same source I use `./build-<variantname>`.

> Or wait, I guess the cmake variable CMAKE_BUILD_TYPE should decide the build type. Most common seems to be Release and Debug. Have to check what this variable contains by default. 

Yep, that's why QtCreator does uses a single build directory with CMake.
AFAIK, `Debug` is the default but it can be overridden by some projects, toolchains or config files.
Also, `CMAKE_BUILD_TYPE` is not used for Visual Studio as it manages itself the corresponding CMake build modes as different VS configurations.

> And the name of the build directory may have the CMAKE_BUILD_TYPE embedded, so you can have different build directories for Debug or Release builds.
> Also, I think the CMAKE_BUILD_TYPE has to be defined manually, but maybe is a good practice to guide new users to define it in the first build.

IMHO, the editor should not be in-charge of the build mode.

**Comment by bbenoist** [comment]
I think that a first reliable solution would be to simply replicate the CMake GUI dialogs for configuring or loading project builds.
As an example, the GUI let its user select a generator and a toolchain when configuring new builds...

**Comment by eidheim** [comment]
Thank you, so the commands will be something like this (from cmake/project-root level):
```sh
mkdir .build #if directory does not exist. This directory can be defined in preferences I guess. 
cd .build
cmake .. # with some way of defining build type using -DCMAKE_BUILD_TYPE=Release for instance
```
?

We have so far avoided having project options, besides the ones defined in CMakeLists.txt. The main issue is a way to define the release type. Could go for Default unless we find this cmake variable defined in the CMakeLists.txt files maybe? And with debug mode we just add Debug?

**Comment by eidheim** [comment]
Or I guess noone would define the build type using set(CMAKE_BUILD_TYPE .. in a CMakeLists.txt?

**Comment by eidheim** [comment]
Ok, so you choose a build type per project, and we somehow have to store this somewhere so that the same build type gets selected next time one opens the same project?

**Comment by eidheim** [comment]
As well as the toolchain for instance. And this have to be chosen before running cmake for the same time. Starting to see the need for a gui for this yes:)

**Comment by eidheim** [comment]
But I still want to open my projects without having to choose a toolchain and release type. Would you mind terribly if we use default settings for this? This would mean that in order to use a different toolchain and built type, one would have run cmake oneself in the given (either default or set in preferences) build-directory with appropriate options. This way we avoid having to create a GUI for this, and we can keep it simple, this being a lightweight IDE and all;)

I think one can read the build setting from cmake cache, so we do not need to store this somewhere else.

**Comment by eidheim** [comment]
Or simply a gui like @bbenoist suggests, but only containing a label where one writes in the cmake parameters (build type and tool chain for instance). We can use the current label system for this (the one used for search and replace for instance). This gui should only be shown if cmake cache is missing I guess.

**Comment by zalox** [comment]
> But I still want to open my projects without having to choose a toolchain and release type.
We should be able to detect build system if the project has CMakeLists.txt or similar indicators from other buildsystems.

**Comment by eidheim** [comment]
I think I need to do some more research to understand 100% what a build system needs, and at the same time make it as simple as possible. As I understand it now, one build directory is a bad idea, as one then needs to recompile a project when swapping back and forth between builds. And a build is at least defined by toolchain (g++ or clang for instance) and CMAKE_BUILD_TYPE (Release or Debug for instance). 

But having several builds in a project, there are issues like for instance: which should be chosen when reopening a project in juci with existing builds? Especially when different toolchains are used. A simple approach would be to use different build directories for only CMAKE_BUILD_TYPE, then at least swapping between Release and Debug is fine.

**Comment by eidheim** [comment]
Although, an issue with using only build directories depending on CMAKE_BUILD_TYPE, is that the cmake cache files have to be removed when switching toolchains for instance. No simple solution in sight yet in other words:)

**Comment by eidheim** [comment]
Although currently I'm leaning towards build directories depending on CMAKE_BUILD_TYPE, and let people needing to change toolchains do this manually instead of using a dialog for this in juCi++.

**Comment by bbenoist** [comment]
> Thank you, so the commands will be something like this (from cmake/project-root level):
> ```
> mkdir .build #if directory does not exist. The directory ".build" can be changed in preferences 
> cd .build
> cmake .. # with some way of defining build type using -DCMAKE_BUILD_TYPE=Release for instance
> ```
> ?

I would rather prefer:

    mkdir build
    cd build
    cmake .. # No assumption on CMAKE_BUILD_TYPE by default. There is no need to force it.

> Edit: changed again since one build directory is maybe simplest, and we then can retrieve the cmake cache

:+1: 

> And the toolchain has to be chosen before running cmake for the first time (unless one take care to remove the cmake cache and its files). Starting to see the need for a gui for this yes:)

:+1: :+1: 

> But I still want to open my projects without having to choose a toolchain and release type.

Like this :wink: :

![cmake-gui](https://cloud.githubusercontent.com/assets/2091902/11827316/69b9de2e-a38b-11e5-8fcf-7cebaa642fc4.JPG)

> Would you mind terribly if we use default settings for this? This would mean that in order to use a different toolchain and build type, one would have to run cmake oneself in the given (either default or set in preferences) build-directory with appropriate options. This way we avoid having to create a GUI for this, and we can keep it simple, this being a lightweight IDE and all;)

Well, you already know [my point of view on this](https://github.com/cppit/jucipp/issues/122), there are way more interesting things to do on the C++ support part :wink: . As such, I don't really mind about choices differing from it... Actually I'm just trying to provide some feedback from my own CMake experience. Decisions behind this remains yours :wink: 

> Or simply a gui like @bbenoist suggests, but only containing an entry where one writes in the cmake parameters (build type and tool chain for instance). We can use the current entry system for this (the one used for search and replace for instance). This gui should only be shown if cmake cache is missing I guess. 

Yep, like CMake GUI :wink: 

> I think I need to do some more research to understand 100% what a build system needs, and at the same time make it as simple as possible.

:+1: 

> ... CMAKE_BUILD_TYPE ... CMAKE_BUILD_TYPE ... CMAKE_BUILD_TYPE ... CMAKE_BUILD_TYPE 

As a remember, here is one of my initial recommendations :

> Do not make any assumption which is only based on both CMAKE_BUILD_TYPE
 and VS default build configurations.

`CMAKE_BUILD_TYPE` is not always used. From [the documentation](https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html) I also linked:

> This variable is only meaningful to single-configuration generators (such as make and Ninja) i.e. those which choose a single configuration when CMake runs to generate a build tree as opposed to multi-configuration generators which offer selection of the build configuration within the generated build environment.

i.e. Rely CMAKE_BUILD_TYPE only if you want to limit support to one ore more single-generators.


Hope this helps :smiley:

**Comment by eidheim** [comment]
Thank you, starting slowly to get it now. So basically we have 4 build alternatives with their own pros and cons:
* Having in-source build 
 * pro: accessing the executable through Run Command with all its sh capabilities is easy.
 * con: leaving cmake generated files and executable directly in the project folder, although when using git and .gitignore this is not really an issue. 
 * con: have to recompile when switching between for instance no build type (CMAKE_CXX_FLAGS is used), Release (CMAKE_CXX_FLAGS_RELEASE is used, with for instance -O3 turned on by default), Debug (CMAKE_CXX_FLAGS_DEBUG is used with -g flag turned on by default). 
* Having one separate build directory (./build by default)
 * pro: no generated cmake files or executable in source directory
 * con: slightly harder to use Run Command
 * con: have to recompile when switching between the 3 build types
 * con: build files are still in the project folder tree, which requires the user to delete the ./build directory when compressing the project to send it to someone (when not using git and .gitignore). Solution here is to use a build directory outside the project tree (../build) but this somewhat messy as the parent directory gets more folders.
* Having several separate build directories (./build/Default, ./build/Release ./build/Debug, or .. instead of .)
 * pros and cons similar to the above item, but:
  * pro: switching between the 3 build types no longer requires recompile
  * con: even harder to use Run Command

**Comment by eidheim** [comment]
Maybe an even better option is to use ./build for default and ./build/debug for debug, and maybe ./build/release for release (but I see no reason to support release since this can be easily done in a terminal anyway).

**Comment by eidheim** [comment]
Note to self: have to add a variable, maybe {project_path_name}, that can be used in preferences to specify for instance build_path: "../build-{project_path_name}" (when using parent directory instead of project directory that is).

**Comment by eidheim** [comment]
Based on http://www.boost.org/doc/libs/1_60_0/libs/filesystem/doc/reference.html#Operating-system-examples ("Characters prohibited in filenames") I'm going with <> for variables in paths and not {}. Thus Tomorrow, I'll create a branch that adds this to your existing preference file (juCi++ fixes this automatically without touching changes you have already done) under `project` as default if you try it out:
```json
  "default_build_path_comment": "Use <project_path_name> to insert the project folder name.",
  "default_build_path": "./build"
```
I'll let you know, and as always, feedback is welcome. Especially if you feel like `"default_build_path": "../build-<project_path_name>"` is a better option.

**Comment by eidheim** [comment]
Thank you all for your comments. You can now try out the new build path solution:
```sh
git clone -b build_dir_fixed --recursive http://github.com/cppit/jucipp
```
