### ISSUE TITLE
Build extensions for existing code-editors instead of a full IDE

### ISSUE THREAD

**Issue by bbenoist** [cppit/jucipp#122]
They are multiple problems which are parts of the IDE equation.

The main ones are:
* Text-editor.
* Task management.
* Debugging integration.
* VCS (e.g. Git)
* Language features (i.e. code-completion, [linting](https://en.wikipedia.org/wiki/Lint_(software)), live-preview, etc.)

As jucipp's primary focus is on advanced capabilities with C++, not on the other items in my list, I find it more efficient to apply the Unix Philosophy :neckbeard: ("do one thing and do it well") and only focus on this part instead of reinventing the wheel again.

I mean, the description of your project clearly emphasizes on C++ support but they are so much more aspects for a code editor to be successful that I doubt it will ever have enough resource for it to be as good as existing solutions...

As an example, they are [2600+](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752459-c-code-completion-and-debugging) votes on adding more C++ features in [VS Code](https://github.com/Microsoft/vscode) which is open source and has some [interesting features](https://code.visualstudio.com/docs/editor/editingevolved), why not simply architecture jucipp as a [language server](https://code.visualstudio.com/docs/extensions/example-language-server) and make it reusable into such editors?

**Comment by eidheim** [comment]
I think it is great that we have alternatives to VS Code. Closing this as it is non-constructive.

**Comment by bbenoist** [comment]
The only non-constructive message here Is yours.

I used arguments to expose my POV and tried to be honest with my troughs. I had serious questions about the real purpose of this project.

Alternatives aren't bad but do we really need yet another one? VS Code was just an example, they are a lot of already existing editors which would appreciate the features you try to implement. All I tried to do is making them available for the masses instead of isolating them.

**Comment by eidheim** [comment]
Sorry, but trying to focus on improvements in our issue section, and not alternatives. I for one am very happy that we now have a quite small project that implements many core functions an IDE needs, and is fast and responsive on top. C++ is a very advanced language, and I do not think you will get a good C++ IDE unless you code it in high level C++ to also cope with the complexity of many features needed in such a project.

**Comment by bbenoist** [comment]
OK, thank you for the clearer explanations.

**Comment by masaeedu** [comment]
@eidheim You seem to have misunderstood the request. The request isn't to implement your C++ analysis in a different language; it is to implement your C++ analysis as a standardized implementation of a protocol-conformant language server so that other editors can benefit from the work.

**Comment by eidheim** [comment]
@masaeedu there already exist decent c++ language server(s) based on libclang. But the problem with using such a server, and not libclang directly, is that you add an additional layer of complexity which will affect memory/cache use and processing time. The additional complexity will most likely also lead to more bugs and require additional development hours, especially in the case of a platform-independent project. Remember, this is a small project developed by a few developers, we need to be careful when prioritising our time:)
