### ISSUE TITLE
Execution fails when a vairable is used in add_executable in CMakeLists.txt

### ISSUE THREAD

**Issue by voldyman** [cppit/jucipp#124]
I use the following command in my project

```
add_executable(${CMAKE_PROJECT_NAME}
   main.cc
   ...
)
```
the build happens but JuiC++ can't execute the binary for some reason.

**Comment by eidheim** [comment]
It should parse cmake code above. Try open a source file within a directory that has add_executable in its CMakeLists.txt, and do run then. The cmake parser is very basic and does not try to detect all your executables in a project.

If this does not work, do you get any error messages?

**Comment by voldyman** [comment]
my project structure is the following
```
proj/
  CMakeLists.txt
  src/
    CMakeLists.txt     # this has add_executable
    main.cc
    libs/
       ....
```

when i open the proj folder in JuiC++, everything is fine, build starts, does the cmake thing the problem occurs during execution
![screenshot from 2015-12-15 12 49 11](https://cloud.githubusercontent.com/assets/2378083/11804529/8f715978-a32a-11e5-9093-50e81a9db0cb.png)

**Comment by eidheim** [comment]
Ok, this is actually a bug:) Use Run Command for the time being as a workaround, and I'll see if I can find the problem Today or Tomorrow.

**Comment by eidheim** [comment]
For instance do Run Command: make && .src/your_executable

**Comment by eidheim** [comment]
Btw, would you mind posting your two CMakeLists.txt? Or maybe send them to eidheim@gmail.com?

**Comment by voldyman** [comment]
no worries,
proj/CMakeLists.txt
```
cmake_minimum_required(VERSION 2.6)
project(tubedl C CXX)

add_subdirectory(src)
```
proj/src/CMakeLists.txt
```
add_subdirectory(libs)

add_definitions("-std=c++1y")

# link with pthreads
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")

#find_package(PkgConfig)
#pkg_check_modules(DEPS REQUIRED
#  pthread
#)

#add_definitions(${DEPS_CFLAGS})
#link_libraries(${DEPS_LIBRARIES})
#link_directories(${DEPS_LIBRARY_DEPS})

include_directories(${LIBEXECUTOR_INCLUDE_DIR}) #header only lib

add_executable(${CMAKE_PROJECT_NAME}
  main.cc
)

add_dependencies(
  ${CMAKE_PROJECT_NAME}
  libexecutor
)
```

**Comment by eidheim** [comment]
Thank you, this will help me figure out the issue.

**Comment by zalox** [comment]
Can you execute the binary outside juci? Do the binary get build with the correct permissions?

**Comment by eidheim** [comment]
The issue is that juci tries to execute the cmake variable:)

**Comment by voldyman** [comment]
i noticed that Jucipp has some problems with cmake (in source builds instead of an independent build dir, etc) 

this might help https://github.com/qtproject/qt-creator/tree/master/src/plugins/cmakeprojectmanager

**Comment by eidheim** [comment]
I think this only affects Compile and Run, or am I wrong?

**Comment by voldyman** [comment]
Yes, this only effects Compile & Run, (are there any other methods to run a compiled program?)

**Comment by eidheim** [comment]
You can start Run Command (alt-enter as default key, you also find it in the Project menu), and then in the entry field write for instance: make && ./your_executable_here

juCi++ remembers your history in Run Command (as well as other methods using similar entry fields), us arrow up/down to access them.

**Comment by eidheim** [comment]
The issue is that CMAKE_PROJECT_NAME is never set in the cmake files, it is an internal cmake variable, which our cmake parser do not know about. It is easily fixed though by creating CMAKE_PROJECT_NAME and PROJECT_NAME from the project-command. I'll fix this Tomorrow, and also try to figure out what other variables the project-command adds. 

Hopefully someone will make a cmake library soon, but until then we have to rely on our own cmake parser.

**Comment by voldyman** [comment]
why don't you adapt the qtcreator's lib for Jucipp?

**Comment by eidheim** [comment]
Qt Creator is quite buggy, and I do not like all the Qcontainers and weird macros. Would prefer either a standalone library or, lacking that, create a good simple, modern and stable solution.

**Comment by zalox** [comment]
I was checking performance on searching through the entire cmake modules folder after the value of the variable, it wasn't that bad, we could add /usr/share/<cmake-paths> in our module to solve this issue I think.

**Comment by eidheim** [comment]
The cmake parser is mostly to figure out the executable, so I think we do not need a full cmake parser, which would also require alot of optimization and most likely be bugprone anyway. If it works in 99% of the cases at least I'm happy until someone makes a cmake library. We have the Run Command alternative too, and that lets you set parameters to the given executable (and other sh functions). I use Run Command far more often than Compile and Run actually. Although this would maybe be abit more tiresome when having build directories.

**Comment by eidheim** [comment]
See PR #129
