### ISSUE TITLE
libclangmm is missing in tarball

### ISSUE THREAD

**Issue by mactkg** [cppit/jucipp#126]
sources of libclangmm is missing in release tarball.
SInce I'm writing formula to build jucipp on Homebrew, I want to include sources of libclangmm to tarball.

```
CMake Error at src/CMakeLists.txt:101 (add_executable):
  Cannot find source file:

    ../libclangmm/src/CodeCompleteResults.cc
```

**Comment by mactkg** [comment]
> SInce I'm writing formula to build jucipp on Homebrew, I want to include sources of libclangmm to tarball.

There is a way to import some resources, I did it.

**Comment by eidheim** [comment]
Thank you for doing this:)
