### ISSUE TITLE
Restructure sourceview functionality

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#13]
Here is a suggestion for a new structure.

![New structure](http://www.guut.org/images/suggestions.png)

**Comment by zalox** [comment]
The thought is to separate each functionality and inherit them by the main view. Also to inject different implementations based on the language of the file, making it possible to turn on gtksourceview syntax highlighing for other languages than c++.

@eidheim what do you think about this?

**Comment by eidheim** [comment]
The Source::Controller will eventually be language-independent, right now the simple indentation methods got to be moved and at some point replaced, and the parse_thread-stuff got to be moved somewhere. 

The way to go might be to subclass Source::View (I guess one Source::View for c/c++/.. code, and this will include the Parser class, and one for using the gtksourceview for the other languages). The Source::View can then be set in the Source::Controller:
std::unique_ptr<Source::View> view; //h-file
//cpp-file somewhere:
view=new ClangView; //view needs to be initialized using constructor, but you see the general idea here
or
view=new GenericView("python");
It will be clearer after I'm finished restructuring source.h/cpp I think.

**Comment by zalox** [comment]
Yeah it is like I suggested above. cstyleview is like clangview, and genericview is sourceview in my diagram. 

For instance I would  like to have functionality such as searchandreplace and undoredo in seperate subclasses of gtksourceviewmm, and the clangview and other subclasses inherit these as needed.

**Comment by eidheim** [comment]
Great, then we think alike:) However, do you need different implementations for searchandreplace and undo in ClangView and GenericView?

**Comment by zalox** [comment]
I think it would help separating the code, but I'm open for other suggestions.

**Comment by eidheim** [comment]
Sorry, I misunderstood. As I thought it: gtksourceview is inherited by a view class that is inherited by (generic)sourceview and (clang)cstyleview. cstyleview should not inherit (generic)sourceview as this class will include code to activate for instance python highlighting. Syntaxhighlighting can be part of cstyleview. 

undoredoview and searchandreplaceview is only needed if there are many improvements/methods compared to what is included in gtksourceview. However, these might be included in a sourceview class instead:
gtksourceview<-sourceview<-genericsourceview
                                            <-clangsourceview
Here both clangsourceview and genericsourceview inherit sourceview(can include undo/redo and search-stuff here) that inherit gtksourceview. What do you think?

**Comment by eidheim** [comment]
I will draw a figure next time:)
