### ISSUE TITLE
Use a project's .clang-format file?

### ISSUE THREAD

**Issue by rpavlik** [cppit/jucipp#133]
It looks like, from the preferences, that there is an enforced clang-format style. Because of the existing, already-filed issues about in-tree builds, I haven't tried this against any of my own big projects, I don't know for sure, but it would be preferable if the app defaulted to using a project's `.clang-format` file (as the `--style=file` command line flag semantics work) before falling back to a system-wide preference.

**Comment by eidheim** [comment]
From http://clang.llvm.org/docs/ClangFormatStyleOptions.html:
"When using -style=file, clang-format for each input file will try to find the .clang-format file located in the closest parent directory of the input file. When the standard input is used, the search is started from the current directory.". 
So I if we find a .clang-format file, we use "-style=file"? I guess clang-format does not understand two -style options? That is for instance: `clang-format -style=file -style="{...}"`?

**Comment by eidheim** [comment]
You can now try out the new build path solution:
```sh
git clone -b build_dir_fixed --recursive http://github.com/cppit/jucipp
```

Feel free to comment, you seem to know cmake better than me.
