### ISSUE TITLE
Make install easier

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#14]
The install of juCi++ should be these commands:

```bash
cmake .
make
sudo make install
```
This can be acquired by making the CMakeLists.txt move them with the install command.

The config and plugins file should also be installed to an appdata-folder.

```bash
.juci #or something in the home directory on unix systems and %APPDATA%-folder on Windows.
```

**Comment by zalox** [comment]
@eidheim I will do this first, since gtk-theming introduces new config files. 

When juci is available with $ make install the data directory will contain the following:
```cpp
~/.juci
    | config.json
    | log _
    |      | juci.log%DATE%
    | theme _
    |        | theme_dark
    |        | theme_light
```

**Comment by eidheim** [comment]
Sounds good!
