### ISSUE TITLE
No tooltips and autocompletion window under Gnome Wayland

### ISSUE THREAD

**Issue by mpsauermann** [cppit/jucipp#147]
Hello,

I've just tested juCi++ on an Arch Linux install running Wayland. The type info tooltips and the autocompletion window just don't show up (even after pressing Ctrl + Space), while they work properly on a normal (i.e. X11) Gnome session. Pressing Ctrl + Space makes the window blink once very quickly. I tried to record the blinking using Gnome's built-in recording, but I got dropped to the login screen as soon as I pressed the mentioned key combination.

Please tell me if you need any additional information.

**Comment by eidheim** [comment]
Have a look at https://wiki.gnome.org/Initiatives/Wayland/GTK%2B. It should be a gtk issue if I'm not mistaken. Our autocomplete system is automatic and asynchronous on C/C++ files, so pressing control-space has no effect. 

It might be that you are scrolling also, or Wayland is detecting scrolling. Try disable these lines:
https://github.com/cppit/jucipp/blob/master/src/source.cc#L448-L453, or other lines in https://github.com/cppit/jucipp/blob/master/src/source.cc#L443-L473.

**Comment by eidheim** [comment]
When I think some more on it, it might be that the tooltips and autocomplete window is getting focus, even though they should not, so try disable:https://github.com/cppit/jucipp/blob/master/src/source.cc#L457-L467

**Comment by eidheim** [comment]
Or at least comment out the hide() functions in https://github.com/cppit/jucipp/blob/master/src/source.cc#L457-L467

**Comment by eidheim** [comment]
You can probably add #ifndef WAYLAND (or something similar) around these hide() functions if this is the case.

**Comment by mpsauermann** [comment]
Commenting out the hide calls in lines 457-467 does help, but then the completion window is misplaced - you can see it [here]
(http://wstaw.org/w/3Jbu/).

But you're probably right that this might be a Wayland issue.

**Comment by eidheim** [comment]
I'll have a look at it Tomorrow, and see if there is anything I can do. The placement issue was strange, the y position does not make sense in any coordinate system.

**Comment by eidheim** [comment]
Is it the same for tooltips?

**Comment by eidheim** [comment]
Maybe the placement is depending on the mouse pointer position?

**Comment by eidheim** [comment]
The problems you are describing are listed here: https://wiki.gnome.org/Initiatives/Wayland/GTK%2B#Popups_and_grabs. The links here are old though, but I found this: http://ftp.gnome.org/pub/gnome/sources/gtk+/3.19/gtk+-3.19.5.changes. Seems like there are alot of Wayland features coming in the 3.20 Gtk+ release. You can also maybe try out the development version 3.19.

**Comment by eidheim** [comment]
Note to self: I might have to do something in the Tooltip constructor (SelectionDialog is fine) when gtk+ 3.20 arrives to support the new grab system.

**Comment by eidheim** [comment]
Saw you were using the Allman bracket style. You might be interested in the new PR #148.

**Comment by mpsauermann** [comment]
Well I can check the tooltips & see if the placement depends on the mouse position if you want to, but I'm not sure if it's worth our time if the bug is on Gtk(mm) side. After all, the IDE seems to work just fine when run with GDK_BACKEND=x11 ;-)

And BTW - you could consider allowing to set the tab width. Now it seems to be locked at 8 and I would prefer to set it to 4, so a single tab would take as much space as 4 spaces.

**Comment by eidheim** [comment]
You mean here tab character \t should be visibly the same as 4 spaces if I understand it. I'll have look.

**Comment by mpsauermann** [comment]
Yes, that's what I mean. Well, to be exact, I think it should be configurable.

**Comment by eidheim** [comment]
Dunno why it is 8 by default, have to see if there is a reason behind this. I'm thinking 4 is a good default value. Will have a look at it Tomorrow, until then you can insert `set_tab_width(4);` into https://github.com/cppit/jucipp/blob/master/src/source.cc#L303 for instance

**Comment by eidheim** [comment]
I think visual tab size equal to 4 spaces is pretty common now, so I hardcoded it. Guess we'll have another discussion if someone disagrees. But in this way we keep the preference file a tiny bit smaller.

**Comment by eidheim** [comment]
Ok, so I'll close this issue, and have a look at it when Gtk+/mm 3.20 arrives. I had a hell of a week when 3.18 came, and I guess it will be pretty much the same when 3.20 is released:) Although, many thanks to the Gtk+ folks for keeping their API modern, the Qt people should learn from this!
