### ISSUE TITLE
When I close all files and open a new file the program crashes.

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#15]
@eidheim this was not happening a few commits ago.

**Comment by eidheim** [comment]
There is a bug with the marking of changed tabs, will fix this monday when im back to civilization!

**Comment by eidheim** [comment]
Fixed in latest pull-request.

**Comment by zalox** [comment]
If you start your commit with #15 you don't need to comment by the way. I.e.

```bash
git commit -m "# Fixes crash on open file."
```
If I then merge a commit with that message the issue is closed automatically.
