### ISSUE TITLE
No way to open an existing project (w/ CMakeLists.txt)?

### ISSUE THREAD

**Issue by amit-jain-SBG** [cppit/jucipp#157]
What it says. In open project menu, if I select an existing folder with cmakelists inside it, juci should open this after asking user, maybe back up cmakelists.txt if it needs to modify it.
Instead right now it just throws up an unhelpful error message that cmakefile exists.
Thanks.

**Comment by eidheim** [comment]
Might need the exact error message. juCi++ never modifies CMakeLists.txt, but I take it you mean CMakeCache.txt? Google the error message and you probably find a solution. 

**If you mean you are using new C++ project, use open folder instead on existing projects. Remembered that new C++ project might output that error message. **

**Comment by amit-jain-SBG** [comment]
Thanks, open folder works. Perhaps rename it to "Open Project" ?

However, I'm not sure the existing CMakeLists.txt is getting used. Im getting warnings like this:
warning: alias declarations are a C++11 extension [-Wc++11-extensions]

whereas CMakeLists.txt contains directives to use C++11:
set_property(TARGET aligner PROPERTY CXX_STANDARD 11)
set_property(TARGET aligner PROPERTY CXX_STANDARD_REQUIRED ON)
set_property(TARGET aligner PROPERTY CXX_EXTENSIONS OFF)

**Comment by eidheim** [comment]
I'm not familiar with the set_property functions, but check compile_commands.json in your build directory and see if it makes sense. This json file is created using cmake and is used by libclang to parse your c++ files.

Btw if you set `set_property(TARGET aligner PROPERTY CXX_EXTENSIONS OFF)` you turn off the c++11 extensions? Try comment out this line?

**Comment by amit-jain-SBG** [comment]
CXX_EXTENSIONS refers to compiler extensions (e.g. gnu++11)

I checked compile_commands.json, it lists all the files to be built and include paths, but none of the compiler options specified in cmakelists are being used in compile_commands.json, e.g.
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}  -DDEBUG -D_DEBUG -DTIMERREPORTER")

I deleted CMakeCache.txt and compile_commands.json and compiled again. Same result.

Also, there should be way to specify CMAKE_BUILD_TYPE without manually editing CMakeLists - in order to switch between debug/release/profile modes. Shall I open another issue for this?

Thanks.

**Comment by eidheim** [comment]
juCi++ has default build and debug build, that is the builds juCi++ needs to work on your files for parsing and/or debugging. The debug build sets CMAKE_BUILD_TYPE to Debug. If you want to use other builds you need to create these manually through cmake commands in a separate build directory. This would be the case if you want to create a Release build:
```sh
mkdir build/release
cd build/release
cmake -DCMAKE_BUILD_TYPE=Release ../..
make
```
Same case, only with different cmake parameters, if you want to create builds for different compilers. We do not want juCi++ to be an OS replacement (like some IDE's maybe are trying to), hence the simplistic design and functionality.

**Comment by eidheim** [comment]
I thought maybe there were a connection between:
```
warning: alias declarations are a C++11 extension [-Wc++11-extensions]
```
and:
```
set_property(TARGET aligner PROPERTY CXX_EXTENSIONS OFF)
```

**Comment by eidheim** [comment]
And if you'd like your default build of a project to be different than what you have specified in preferences, you can create the build manually and run cmake there yourself, for instance:
```sh
rm -r build
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER=g++-5 ..
```
And juCi++ will use this as your default build. You can create a custom debug (build/debug) build in similar manner.

**Comment by amit-jain-SBG** [comment]
Hi,

I take your point about keeping things simple. But there are still 2 issues:

Hi,

1. Compiler arguments are not getting generated in the Makefile or compile_commands.json. I just verified this by attempting to make a debug build (_DEBUG and TIMEREPORTER were not defined on compiler command line, even though specified as CMAKE_CXX_FLAGS_DEBUG). This is a show stopper for me, and is probably related to c++11 not getting set either.

2. default CMAKE_BUILD_TYPE is debug anyway. So, wen not in debug mode you should call cmake with -DCMAKE_BUILD_TYPE with release, or let the user specify a default build type somewhere.

Thanks.

**Comment by amit-jain-SBG** [comment]
A thought occurred:

Could these problems be relate to the fact that the first line in my CMake script is:
cmake_minimum_required(VERSION 3.0)

This is because CXX_STANDARD is only supported by 3.0+. My installed version is 3.0.2.

**Comment by eidheim** [comment]
Would you mind posting your compile_commands.json? juCi++ does creates this through `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`, you can also try to create this file yourself outside juCi++ and see if there is a different result. 

If I remember it correctly:
 * default build is without debug and optimization
 * debug build is with debug
 * release is without debug and with optimization.

**Comment by eidheim** [comment]
I suggest you create your build and build/debug directories yourself if you have a very special setup for a project:
```sh
mkdir build
cd build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON [your parameters] ..
```
Now juCi++ will not touch your build setup at all. Do the same with build/debug.

**Comment by amit-jain-SBG** [comment]
Manually generated file attached. juci generated one has no flags in compiler comands.

Command I used: alignment/build/debug$ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../..

[compile_commands.txt](https://github.com/cppit/jucipp/files/111321/compile_commands.txt)

**Comment by amit-jain-SBG** [comment]
OK, your last suggestion is helpful. This lets me build the project :)

Best,

**Comment by eidheim** [comment]
It is still strange that -g gets activated without `-DCMAKE_BUILD_TYPE=Debug`. Might be that you have set environment variables that are not set inside juCi++ (for instance you have not stored them in an shell init file). See the environment variables from inside juCi++ by running Project->Run Command: `export`.

**Comment by amit-jain-SBG** [comment]
Oh, I don't know about -g since juci does not create a compile_commands.json when asked to debug.

**Comment by eidheim** [comment]
compile_commands.json is only needed when parsing (using default build). juCi++'s parameters when creating builds: 
* `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` for default build (./build)
* `-DCMAKE_BUILD_TYPE=Debug` for debug build (./build/debug)
