### ISSUE TITLE
[Help]I am in the link problem, My env is in ubuntu 15.04

### ISSUE THREAD

**Issue by timloo0710** [cppit/jucipp#158]
I follow the install.md. 

in the "sudo make install", 

There are errors in linking:

Linking CXX executable juci
CMakeFiles/juci.dir/juci.cc.o: In function `Application::on_command_line(Glib::RefPtr<Gio::ApplicationCommandLine> const&)':
/home/timloo/CPP_EXS/jucipp/src/juci.cc:(.text+0x51): 未定義參考到「Glib::set_prgname(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)」
...............................................................................

I add a little code in the 
src/CMakeLists.txt
........................................
link_directories(
  ${GTKMM_LIBRARY_DIRS}
  ${GTKSVMM_LIBRARY_DIRS}
  ${Boost_LIBRARY_DIRS}
  ${LIBCLANG_LIBRARY_DIRS}
)
#----- test 
message(STATUS "GTKMM_LIBRARY_DIRS: ${GTKMM_LIBRARY_DIRS} ")
message(STATUS "GTKSVMM_LIBRARY_DIRS: ${GTKSVMM_LIBRARY_DIRS} ")
message(STATUS "Boost_LIBRARY_DIRS: ${Boost_LIBRARY_DIRS} ")
message(STATUS "LIBCLANG_LIBRARY_DIRS: ${LIBCLANG_LIBRARY_DIRS} ")
................................................
and 

cmake ..

It shows

-- GTKMM_LIBRARY_DIRS:  
-- GTKSVMM_LIBRARY_DIRS:  
-- Boost_LIBRARY_DIRS: /usr/lib/x86_64-linux-gnu 
-- LIBCLANG_LIBRARY_DIRS:  
 

In my env, three libs are not found,  is there any help? Thanks!!

**Comment by eidheim** [comment]
I have seen the same problem before when someone was trying to compile juCi++ with clang++ instead of g++. It is important to compile with g++ since the libraries you use are also compiled with g++ (ABI differences most likely). Would you mind post the entire output of `cmake ..`?

**Comment by eidheim** [comment]
To compile juCi++ with g++ instead of clang++ (if this is the problem), replace the cmake command in the install docs with:
`cmake -DCMAKE_CXX_COMPILER=g++ ..`

**Comment by timloo0710** [comment]
Thank you very much!!

I append following two in the CMakeLists.txt:

set(CMAKE_C_COMPILER /usr/bin/gcc)
set(CMAKE_CXX_COMPILER /usr/bin/g++)

And the linking message is very different!!

The undefined part is off, 

But it showed:
--------------------------------------
Linking CXX executable juci
/usr/bin/ld: cannot find -lclang
collect2: error: ld returned 1 exit status
-------------------------------------

**Comment by eidheim** [comment]
Would you mind posting the output of your cmake command?

**Comment by timloo0710** [comment]
ok, Thank you, 
My output is:

:~/CPP_EXS/jucipp/build$ cmake ..
-- The C compiler identification is Clang 3.6.0
-- The CXX compiler identification is Clang 3.6.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found LibClang: /usr/lib/llvm-3.6/lib/libclang.so  
liblldb not found. Compiling juCi++ without debugging support
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   thread
--   log
--   system
--   filesystem
--   regex
-- checking for module 'gtkmm-3.0'
--   found gtkmm-3.0, version 3.14.0
-- checking for module 'gtksourceviewmm-3.0'
--   found gtksourceviewmm-3.0, version 3.2.0
-- Found ASPELL: /usr/lib/x86_64-linux-gnu/libaspell.so

**Comment by eidheim** [comment]
Have you added "-lclang" to the CMakeLists.txt somewhere, or done some other changes? It should link to /usr/lib/llvm-3.6/lib/libclang.so (with full path). And you still get the following output:
```sh
-- The C compiler identification is Clang 3.6.0
-- The CXX compiler identification is Clang 3.6.0
```
Try the following (fresh git clone):
```sh
git clone --recursive https://github.com/cppit/jucipp
mkdir jucipp/build
cd jucipp/build
cmake -DCMAKE_CXX_COMPILER=g++ ..
make
```

**Comment by timloo0710** [comment]
Thanks, 

I changed it, 

:~/CPP_EXS/jucipp/build$ cmake -DCMAKE_CXX_COMPILER=g++ ..
-- The C compiler identification is Clang 3.6.0
-- The CXX compiler identification is GNU 4.9.2



It is something strange in my env, 

Those two
 GTKMM_INCLUDE_DIRS:
 GTKSVMM_INCLUDE_DIRS:

are found, 

Those two 
-- GTKMM_LIBRARY_DIRS:  
-- GTKSVMM_LIBRARY_DIRS: 
are not found. 

And this

LIBCLANG_LIBRARY_DIRS:

not found. 

--------------------------------------------------------
And finally it is linking ok. 

Thanks

**Comment by eidheim** [comment]
The LIBRARY_DIRS are not important when the libraries are given with full path. 

Glad it worked eventually.

**Comment by eidheim** [comment]
Btw, I'll do a quick check later on Ubuntu 15 myself, since I saw lldb was not found. Might be because you did not install the same version as libclang, but it might also be that it is not found by our CMakeLists.txt.

**Comment by timloo0710** [comment]
![myjuci](https://cloud.githubusercontent.com/assets/8321/12777151/e05a8b38-ca95-11e5-9f2f-47e04e19c5ac.png)

it is ok, in my pc, thanks

**Comment by eidheim** [comment]
In case you want debug support in juCi++ do the following:
'''sh
sudo apt-get install liblldb-3.6-dev
git clone --recursive https://github.com/cppit/jucipp
mkdir jucipp/build
cd jucipp/build
cmake -DCMAKE_CXX_COMPILER=g++ ..
make
sudo make install
'''

I think you forgot to install liblldb-3.6-dev when installing the dependencies. Just tested this on Ubuntu 15.

**Comment by timloo0710** [comment]
Thank your kindness.

I follow the wrong install step,  install lldb-3.5, it makes juCi++ 's
debug function is disabled,
I remind you ever talked about.

So I install the  liblldb-3.6-dev, actually I copy the right whole  "sudo
apt-get ......" to install .

cmake again,  the debug function is enabled, Thank you very much!!juCi++ is
so amazing.

It is easier than the vim plugin "YCM"(you complete me).

 Best regards, Tim

2016-02-03 19:51 GMT+08:00 Ole Christian Eidheim <notifications@github.com>:
