### ISSUE TITLE
[LLDB] Jucipp crashes when compiled with lldb support

### ISSUE THREAD

**Issue by entd** [cppit/jucipp#164]
Jucipp crashes on my Linux 64 bits system when lldb is provided.
Project compiles right without any problems, but when I start it just crahes with warning:
`: CommandLine Error: Option 'aarch64-reserve-x18' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options`
I managed to build and launch it without any problems, when lldb was disabled (removed from system).

**Comment by eidheim** [comment]
We need some more information. What platform are you on? What is the error message?

**Comment by entd** [comment]
Sorry I messed up clicked a submit issue without writing comment.
My system is s little bit not standard - manjaro. But it uses mostly unmodified upstream packages, so probably this can be reproduced with newest LLDB (on my system it is 3.7.1-1 version).

**Comment by eidheim** [comment]
Manjaro is based on Arch Linux, which has an issue with respect to lldb (see installation notes):
https://bugs.archlinux.org/task/47811?project=1&cat%5B0%5D=2&string=lldb
Feel free to vote up this Arch Linux issue:)

**Comment by zalox** [comment]
This issue is persistent with my lldb-issue on arch. 
It's due to an error in the arch lldb package.
I haven't produced a work around yet. Since Manjaro is based on Arch it's not so wage to suggest this.

The lldb-AUR-package is also broken.
