### ISSUE TITLE
jucicpp as neovim gui client

### ISSUE THREAD

**Issue by 8l** [cppit/jucipp#167]
Hi, i want to use jucipp as neovim gui client, like neovim-qt.
https://github.com/equalsraf/neovim-qt

TIA

**Comment by eidheim** [comment]
Could you elaborate? Not sure if I understand the issue.

**Comment by 8l** [comment]
i want to use vim mode in jucipp, this is practical approach, IMHO.
that's all.

**Comment by eidheim** [comment]
Then this is a duplicate of #163. Please see this issue, and the suggestions we have there, especially have a look at this link: http://vim.wikia.com/wiki/Vi_key_bindings_in_gtk.

**Comment by eidheim** [comment]
And feel free to post your solution if you find a way to do this without altering the juCi++ source code.
