### ISSUE TITLE
Enhancement requested in Find (ctrl+F) dialog

### ISSUE THREAD

**Issue by amit-jain-SBG** [cppit/jucipp#170]
- please consider supporting incremental find in active window, as user types in dialog

- dialog should have 2 action buttons: find next, find previous

- Some options also: find in all open windows, find in all project files (should open file)

Thanks.

**Comment by eidheim** [comment]
For next and previous, press enter and shift-enter in the search entry. I guess its pretty common nowadays to leave out the next and previous buttons. Not sure about the incremental find though. Think its nice that the window does not scroll before one press enter, especially when you have the highlighting as you type. 

Regarding the last item, find in all project files etc, I guess you could use Project->Run Command here instead. juCi++ does not try to be an OS, or at least such functions will not be prioritised at the moment. However, feel free to make a pull request for such items.

**Comment by milleniumbug** [comment]
Having Enter/Shift+Enter is fine, but by itself is terrible from UX standpoint: no discoverability.

However, buttons with text "Find previous"/"Find next" would be way too big: my suggestion: button with up-arrrow for "Find previous" and a button with down-arrow for "Find next".

> [^][v]

**Comment by amit-jain-SBG** [comment]
I hate Enter because it is also a character keystroke - so have to be mindful of focus while the dialog is up. I see F3 & Ctrl+F as pretty much standard for find command.

Visual Studio, Codelite, Code:Blocks, Eclipse, even Firefox all support find as you type.

Find in project is important for one simple reason: visually verifying that refactoring worked as expected.

And please, please provide a simple option to reload last opened project upon startup :)

Thanks.

**Comment by eidheim** [comment]
We do not try to copy other IDE's, and scrolling the buffer when you write in the search entry make you loose track of where you were. I guess we could add arrows at the search box, but we try not to force use of the mouse when working on a buffer.

I guess I can add ~/.juci/last_session.json though, to open last session folder and tabs:)

**Comment by eidheim** [comment]
@amit-jain-SBG See the commit above.

**Comment by eidheim** [comment]
@amit-jain-SBG See also #171

**Comment by amit-jain-SBG** [comment]
👍😁

**Comment by eidheim** [comment]
I have given the next-previous buttons some more though, and the problem is that if we add them, we should add replace next and replace previous buttons as well. So I think its best to leave them out, and thus keep the number of buttons in the search box to a minimum. 

The focus is set automatically, so using enter and shift-enter should not be a problem. Just hit escape after you are done with the search to get back to the buffer. 

Also the search updates when you switch tabs while having the search entry up, and that is one way to verify the result of a refactor.

**Comment by milleniumbug** [comment]
I see no reason why "Replace previous"/"Replace next" should exist: they're equivalent to running "Find previous"/"Find next" and doing replacing in-place. That would make one of these buttons redundant:

> `[^][R][v]`

The most important feature of these buttons would be having a on-hover tooltip, something like "Find Next (press Enter on a Find textbox)" or "Find previous (press Shift+Enter on a Find textbox)" - that way you could introduce the feature to the user. (I don't know any program that does "Find previous" on Shift+Enter)

Speaking of Find dialog - some info about dialect of regex (it helps that we have so many) and style of backreferences (\1, $1, ...) would be useful. Not necessarily in the program, but at least in documentation.

**Comment by eidheim** [comment]
I agree that [^][R][v] with tooltips might work. You can probably find some UTF-8 characters for the up/down arrows. Feel free to make a pull request, I have some other work I need to prioritise before this. Adding the help wanted label:)
