### ISSUE TITLE
MSYS2: recent build and linking problems, and segmentation faults

### ISSUE THREAD

**Issue by oalbe** [cppit/jucipp#172]
Hey there,

I hate bothering but I figured this has the potential to be something you might be interested in knowing, so I convinced myself in posting it.

I was very interested in trying Juci so I went through the step-by-step instructions you wrote about building and running it. I did everything the exact same way you suggested, but things went south anyway.

Basically, everything goes smoothly during compilation. No complains from CMake, no problems with MSYS2. The problem happens when I try to run it. If I run it from the shell, it just says some library is missing. When I try executing from Explorer instead, it complains about a specific missing library (`libicuuc56`).

```plain
C:/dev/msys64/mingw32/bin/juci.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

So I passed the executable through Dependency Walker, and I discovered that there are actually 7 _things_ that seem to be missing (specifically, DW says for each of those: _Error opening file. The system cannot find the file specified(2)_):

- API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
- API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
- API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
- LIBICUUC56.DLL
- API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
- EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL
- IESHIMS.DLL

I checked the `bin/` folder, and there actually is a `libicuuc` dll, but it's `55` instead of `56`. I have no idea where this dll comes from, so I don't know how to fix it and try again.

Some details:

- I installed it for x86 (changing `x86_64` to `i686` in the packages names and in the `cmake` command) despite having a 64bit OS. I did it simply because I use the MSYS2 Win32 shell daily, and I already had some of the packages installed.
- I am on Windows 8.1 laptop, 64bit.
- `git clone` complained several times about "': not a valid identifierline 89: export: `name"`, and I honestly have no idea what this means. But it cloned the repo anyway.
- `make` completed without any problem at all.
- `make install` output:

```plain
[100%] Built target juci
Install the project...
-- Install configuration: ""
-- Installing: C:/dev/msys64/mingw32/bin/juci.exe
```

I think it's everything. If there are other details you might need, don't hesitate to ask, I'll be happy to provide them.

**Comment by eidheim** [comment]
I managed to get the needed dll's by running (from where you ran your git command):
```sh
objdump -p ./jucipp/build/src/juci.exe |grep "DLL Name"
```
My output is as follows:
```sh
        DLL Name: libaspell-15.dll
        DLL Name: libatkmm-1.6-1.dll
        DLL Name: libboost_filesystem-mt.dll
        DLL Name: libboost_log-mt.dll
        DLL Name: libboost_regex-mt.dll
        DLL Name: libboost_system-mt.dll
        DLL Name: libboost_thread-mt.dll
        DLL Name: libclang.dll
        DLL Name: libgdk-3-0.dll
        DLL Name: libgdkmm-3.0-1.dll
        DLL Name: libgio-2.0-0.dll
        DLL Name: libgiomm-2.4-1.dll
        DLL Name: libglib-2.0-0.dll
        DLL Name: libglibmm-2.4-1.dll
        DLL Name: libgobject-2.0-0.dll
        DLL Name: libgtk-3-0.dll
        DLL Name: libgtkmm-3.0-1.dll
        DLL Name: libgtksourceview-3.0-1.dll
        DLL Name: libgtksourceviewmm-3.0-0.dll
        DLL Name: libpangomm-1.4-1.dll
        DLL Name: libsigc-2.0-0.dll
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: libwinpthread-1.dll
        DLL Name: USER32.dll
        DLL Name: libgcc_s_seh-1.dll
        DLL Name: libstdc++-6.dll
```
Is your output similar? However, I ran `pacman -Suy` Today. Some of the issues in MSYS2 earlier has been related to not having upgraded MSYS2.

**Comment by oalbe** [comment]
I ran that command, and the output is actually almost identical (it changed the order of some DLLs actually, but I assume that doesn't count).

The only difference was that my output has this library: `DLL Name: libgcc_s_dw2-1.dll` while yours has this one: `DLL Name: libgcc_s_seh-1.dll`.

Yeah I thought about upgrading the whole MSYS2, problem is that I don't have a great connection at hand at the moment, so it would take a while. (I'll try doing it tomorrow in the morning if the connection doesn't decide to crash)

**Comment by eidheim** [comment]
Hope that fixes it. You probably have to remove the build directory and run cmake and make again for juci to work after the upgrade. And make sure to run juci from the correct mingw shell, but I guess you know that:)

**Comment by eidheim** [comment]
You might have to restart the mingw shell too after the upgrade.

**Comment by eidheim** [comment]
Due to MSYS2 upgrade to gtk3.20 packages Tonight, juCi++ is currently broken on a freshly upgraded MSYS2. I'll have a look if there is a quick fix for this.

**Comment by oalbe** [comment]
Oh, cool, so this is why at some point even `gtkmm3` was complaining about missing libraries. Too bad I already went the way of making a clean installation of MSYS2 because I thought I made a mess. Glad to know it wasn't due to me possibly breaking things.

I'll wait :)

**Comment by eidheim** [comment]
Follow https://github.com/Alexpux/MINGW-packages/issues/1236

Also regarding the cmake gtkmm3 issue, `pkg-config --exists --print-errors gtkmm-3.0` gave this output:`Package 'libpcre', required by 'glib-2.0', not found"`. However this is resolved by installing mingw-w64-pcre.

**Comment by eidheim** [comment]
I posted this bug at GNOME Bugzilla: https://bugzilla.gnome.org/show_bug.cgi?id=764233

**Comment by eidheim** [comment]
Getting close to a fix, but gtksourceview3 probably have to release gtksourceview3.20.1 for it to work on Windows. However, if that takes time, I could add a couple of patches to the current MSYS2 gtksourceview3 package and ask for rebuild.

**Comment by eidheim** [comment]
There is also a segmentation fault when running juCi++ in MSYS2, but that is easy to fix compared to GTK macros! I'll fix the segmentation fault later.

**Comment by oalbe** [comment]
Great news!

It shouldn't be that hard to add the patches to the MSYS2 packages during the build process (I learned how to do it and it's not hard at all). So even the patch route might be feasible.

**Comment by eidheim** [comment]
Sorry for being a bit lazy, but hoping they will bump the gtksourceview micro version because of the two patches (https://bugzilla.gnome.org/show_bug.cgi?id=764246 and https://bugzilla.gnome.org/show_bug.cgi?id=764263). Or else they do not have a working Windows port. 

I have not looked at the segmentation fault yet, but its due to the MSYS package upgrades the other day. Feel free to investigate, I'm taking a break Tonight, these gtk minor version upgrades are time consuming!

**Comment by eidheim** [comment]
Ok, I looked a bit on the segmentation fault, and it seems there are several issues. For some reason only boost::property_tree::ptree::get<std::string> is working, that is not <bool> for instance. And, after fixing the ptree issue, when opening a file, another segmentation fault is within filesystem::read_non_utf8. I'll probably fix these things Tomorrow.

**Comment by eidheim** [comment]
Removing -O3 from top of src/CMakeLists.txt fixes most of the segmentation faults. However, clang_CompilationDatabase_fromDirectory from libclang still causes segmentation fault.

**Comment by eidheim** [comment]
All right, we are getting close to a working MSYS2 version again! Give it a day or two.

**Comment by eidheim** [comment]
The issues has been solved. Just waiting for https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gtksourceview3 to be rebuilt (probably Tonight). Closing this issue then.

**Comment by oalbe** [comment]
That's great! I wish I was able to be of any help in this.

**Comment by eidheim** [comment]
Still waiting for mingw-w64-gtksourceview3 to be rebuilt for version 3.20.1. Do you know how MSYS2 queue their builds? Have not been able to find any information on this.

**Comment by eidheim** [comment]
Upgrade with `Pacman -Syuu` and you should now be able to install juCi++ on MSYS2 when following the installation instructions:)

**Comment by oalbe** [comment]
> Do you know how MSYS2 queue their builds?

Mh, I don't know how the guys queue builds, but I doubt they actually have a queue. You can try asking in #msys2 on OFTC.net network. They are all nice people :)

I'll try the upgrade and the new installation as soon as possible (which probably means on Sunday, unfortunately :/) let's keep finger crossed. Thanks for the interest and the help!
