### ISSUE TITLE
opening up enough tabs hides the minimap

### ISSUE THREAD

**Issue by milleniumbug** [cppit/jucipp#176]
Before:
![before](http://i.imgur.com/PrjKylV.png)
After:
![after](http://imgur.com/JLpnIu5.png)

If I open one more tab, the minimap disappears completely.

**Comment by eidheim** [comment]
Thank you. However, although unrelated, are the errors (red underlines) on the first image supposed to be there?

**Comment by milleniumbug** [comment]
They most probably aren't, this'll probably be the subject of another issue.

**Comment by eidheim** [comment]
I never get errors unless they should be there. If you manage to create a simple test case with incorrect errors sometime that would be great.

**Comment by eidheim** [comment]
When I think about it, it might be because you have not set the c++11 standard or higher in CMakeLists.txt. Pre c++11 will yield those errors.
