### ISSUE TITLE
the IDE doesn't pick up standard settings and include directories

### ISSUE THREAD

**Issue by milleniumbug** [cppit/jucipp#177]
Opening up the project https://github.com/milleniumbug/juci_issue_reproducing_1/tree/4c44d5c9278b61662e6ef3f0fde725fb8a70480c in juCi++ shows errors (Clang seems to think it's in C++03 mode and it doesn't have any added include directories)

https://imgur.com/a/d4PAn

This is the content of the `compile_commands.json` file:

```
[
{
  "directory": "/home/milleniumbug/dokumenty/PROJEKTY/InDevelopment/sample_test/build",
  "command": "/usr/lib64/ccache/c++    -I../include   -std=c++11 -Wall   -o CMakeFiles/sample_test.dir/main.cpp.o -c /home/milleniumbug/dokumenty/PROJEKTY/InDevelopment/sample_test/main.cpp",
  "file": "/home/milleniumbug/dokumenty/PROJEKTY/InDevelopment/sample_test/main.cpp"
}
]
```

I'm on Fedora, running juCi++ cloned from commit 31343961dade904e941147a27bc7b2d485e144ba

**Comment by eidheim** [comment]
Strange that your include (`-I../include`) is not an absolute path. What version of cmake do you have? I'll check other OS'es. 

Regarding the .hpp file, a temporary solution is to add an empty CMakeLists.txt in the include directory. Currently, juCi++ searches for these files to find the project root (the CMakeLists.txt with `project()` set). I'll see if I can fix that in some decent way. Maybe do an exception on header-files, as implementation files normally have a CMakeLists.txt in its path.

**Comment by eidheim** [comment]
The problem goes away with header files and implementation files in the same directory, with a CMakeLists.txt in this directory.

**Comment by milleniumbug** [comment]
`cmake --version` says this:

> `cmake version 3.4.1`

Speaking of errors I have similar issues when opening juCi++ itself in the IDE which I can't explain at all. Opening `source_clang.cc` is especially problematic.

https://imgur.com/a/nXEtn

To be honest, I wouldn't be surprised if clang would be totally broken on Fedora, I'll try on another system when I'll have the time.

**Comment by zalox** [comment]
I sometimes get these full pages with red lines when there are errors related to preprocessor macros.

**Comment by eidheim** [comment]
In general, I think its a good idea to use `${CMAKE_SOURCE_DIR}` when specifying project directories, for instance: 
```cmake
include_directories("${CMAKE_SOURCE_DIR}/include")
```
I have cmake version 3.5.1 but I'll check on older systems.

**Comment by eidheim** [comment]
Opening `source_clang.cc` at least works without errors on Debian stable/testing, Ubuntu 14/15, Mint (both versions), MSYS2, ArchLinux and OS X.

**Comment by eidheim** [comment]
@milleniumbug even the old Ubuntu 14 adds absolute paths to -I headers directories in compile_commands.json (cmake version 2.8). But as I understand it, use `${CMAKE_SOURCE_DIR}` as in `include_directories("${CMAKE_SOURCE_DIR}/include")` to make sure your CMakeLists.txt is platform independent.

**Comment by milleniumbug** [comment]
I've finally found out why the paths were relative: this was due to non-default settings I had for CMake command. If using `cmake -G Ninja`, the paths are relative.

**Comment by eidheim** [comment]
Thank you, that helped a lot. Was able to fix this by adding `-working-directory`, set to the build directory, to the libclang arguments when creating the translation unit. I'll commit a fix for this soon.

**Comment by eidheim** [comment]
@milleniumbug Problem should be fixed now. You can continue using Ninja.

**Comment by milleniumbug** [comment]
Awesome! I'll let you know if there are any more problems.
