### ISSUE TITLE
The Terminal should use monospace font

### ISSUE THREAD

**Issue by adiultra** [cppit/jucipp#179]
The terminal below the editor, that logs all actions and is Used to take input If I run a program with `cin`, can be improved by having mono space font.

Also, When the code runs, It can clear the screen so it is more intuitive that the code is running fine and input can be made.

Also, Also, Tab height can be increased.

PS. Your project is one of the first programs that safely and successfully compiled and installed from source.

**Comment by milleniumbug** [comment]
+1 for "Clear terminal" feature. Must-have for debugging several screens of error messages :D

**Comment by eidheim** [comment]
@adiultra : increased tab height? Would you mind posting me a screenshot of your juCi++ tabs, and which theme are you using?

These things should be doable. Guess we can use the same font in the terminal as in the source view. I guess its ok to clear the terminal when doing compile/run/debug then?

**Comment by zalox** [comment]
I think we should have an option for clearing on compile. The default option can be to clear, but I'd like to be able to force it.

The tab height can be adjusted in your gtk-theme. We could add a way to make small adjustments to the gtk-theme in the config directory.

We should also make the font from the terminal a separate config. Some people might like it less verbose with a less spacy font.

**Comment by eidheim** [comment]
Check out https://github.com/eidheim/jucipp/tree/suggestion-terminal-and-fonts and let me know what you guys think. 

@zalox regarding gtk css/theme: there are default setting files for this that gtk looks for already. We should not add our own files for this in `~/.juci`.

**Comment by milleniumbug** [comment]
I'm not sure if having "the terminal" is the solution, I wonder if there should be multiple terminals, currently all output is multiplexed into one. One could have compiler errors displayed on one, debugging messages in another, and the rest on yet another... what do you think?

**Comment by eidheim** [comment]
@milleniumbug I love having one terminal in the IDE, but that's me. If I want more terminals I open a terminal in my OS. More than one terminal is more confusing than its worth I think.

**Comment by eidheim** [comment]
I reverted the directories font change in https://github.com/eidheim/jucipp/tree/suggestion-terminal-and-fonts.

**Comment by zalox** [comment]
@milleniumbug I agree with @eidheim. To keep the IDE lightweight and simple we should keep the number of terminals as is.

We could however categorise (internally) or filter (externally) some of the output to handle very verbose programs. It might be useful to for instance turn off juci++ output completely and only handle output from compiling/running. I'm not certain about this, and would like some input. 

_Sidenote: With an categories of output it would be possible to add more terminals through plugins. The latter however constructs concerns about race conditions for the plugin developer._

**Comment by eidheim** [comment]
Also made the terminal font size slightly smaller than the source font size in the above commit. I like the simplicity of having one font setting, at least for now:)

**Comment by zalox** [comment]
```c++
source.font=source_json.get<std::string>("font");
terminal.font=source_json.get<std::string>("termial_font", source.font);
```

Something like this maybe? Then we can omit the option from the config file.

**Comment by eidheim** [comment]
@zalox I have the solution I think:
* Add terminal.font set as "" default, with font_comment: "Set empty to use 0.95*source.font size"
* Add project.clear_terminal_on_compile or something similar, default: true
* move terminal_history_size to terminal.history_size, and implement removing deprecated config items like terminal_history_size automatically. Especially this one might take some hours, so I'll postpone this work till after work Wednesday.

**Comment by milleniumbug** [comment]
Fair enough, the @zalox suggestion seems to be more interesting in general, since it could solve my problem - I'll make a prototype soon.

**Comment by eidheim** [comment]
@zalox and @milleniumbug (regarding internal/external output) juCi++ will help you with standard in, out and err. Any other output should go through a logger singleton class storing info in a file for instance, and one should use an external viewer for this. I say this again, and will probably say it many more times: juCi++ will never try to replace your OS:)

**Comment by adiultra** [comment]
Sorry for being late for replying. Thanks for the font change. It's quite effective.

Here is the screen-shot. I am Using Arc.

![screenshot-juci](https://cloud.githubusercontent.com/assets/12121575/14256065/dc9f85f8-fab4-11e5-9566-30034c852d92.png)

**Comment by eidheim** [comment]
Thank you for the screenshot, the tab heights are as intended to save vertical space.
