### ISSUE TITLE
Debugging: lldb on Manjaro

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#191]
The issue reported in https://bugs.archlinux.org/task/47811?project=1&cat%5B0%5D=2&string=lldb seems to be fixed in lldb 3.8.0 (https://llvm.org/bugs/show_bug.cgi?id=24953). Closing this issue when lldb gets upgraded on Arch Linux.

**Comment by eidheim** [comment]
Update: lldb 3.8.0 is currently in Staging: https://www.archlinux.org/packages/?q=lldb

**Comment by zalox** [comment]
I'm really looking forward to debugging on my main PC!

**Comment by eidheim** [comment]
Upgrade arch, install lldb, rebuild juCi++ and debug now works!

Closing this issue when Manjaro gets the new llvm/lldb packages.

**Comment by eidheim** [comment]
@archshift You can now add lldb to the [jucipp-git](https://aur.archlinux.org/packages/jucipp-git/) dependencies I think.

**Comment by eidheim** [comment]
@archshift I added a comment on https://aur.archlinux.org/packages/jucipp-git/ about the missing dependency: lldb
