### ISSUE TITLE
Problem with install instructions for MSYS2

### ISSUE THREAD

**Issue by klusekrules** [cppit/jucipp#193]
When I try install the juci on windows using MSYS2 when executed line
```
cmake -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw64 ..
```
I received  error:
```
CMake Error: Could not create named generator MSYS Makefiles
```
I can't not find reason of this error. Could you help me with this problem?

**Comment by zalox** [comment]
CMake got updated last night. It might be related.

https://github.com/Alexpux/MINGW-packages/pull/1312

**Comment by eidheim** [comment]
Try upgrade your system with `pacman -Syuu`

**Comment by eidheim** [comment]
I got the exact same message when trying to run cmake in the MSYS shell. Use a MinGW Shell (for instance MinGW-w64 Win64 Shell) instead. I'll update the installation documents.
