### ISSUE TITLE
"Unknown Application Name" menu entry on Ubuntu 16.04

### ISSUE THREAD

**Issue by hwidth** [cppit/jucipp#201]
I'm assuming this should have been "juCi++" instead?

Latest source from master branch, Ubuntu 16.04, followed usual instructions for building on Ubuntu.

Menu contains the About, Preferences, Quit options.

![Ubuntu 16.04](https://dl.dropboxusercontent.com/u/22370817/Screenshot%20from%202016-04-28%2021-47-05.png)

**Comment by hwidth** [comment]
This happens only when starting from command line.. Starting from dash shows the expected "juCi++" menu entry

**Comment by eidheim** [comment]
Ubuntu has some issues with gtk menus. If you log in and out the application name will show correctly.

**Comment by hwidth** [comment]
Indeed, closing.
