### ISSUE TITLE
Slow parsing of header files

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#210]
When working in .hpp and .h files it seems that semantics are a lot slower, is that intended?

**Comment by eidheim** [comment]
It is because libclang is rebuilding caches when header files are modified. I'm aware of this, but have not yet found a solution.

**Comment by eidheim** [comment]
I did try some tricks like making libclang think it was working with a implementation file instead of a header file, but I failed, at least so far, to achieve improved processing speed.
