### ISSUE TITLE
Can't remove breakpoints

### ISSUE THREAD

**Issue by milleniumbug** [cppit/jucipp#212]
While the debugged program is running, breakpoints can't be removed (that is, juCi acknowledges the breakpoint removal by removing line highlighting, but the actual breakpoint isn't removed and LLDB stops on it anyway).

Quick debugging reveals that it's not removed because `breakpoint_path==file_path` is false at `debug_clang.cc:465` because `breakpoint_path` is `"/home/milleniumbug/dokumenty/PROJEKTY/NotMine/jucipp/build/debug/../../src/debug_clang.cc"` and `file_path` is `"/home/milleniumbug/dokumenty/PROJEKTY/NotMine/jucipp/src/debug_clang.cc"`

I assume using `boost::filesystem::equivalent` instead would fix the problem.

**Comment by eidheim** [comment]
Thanks for investigating it! Do you have an idea why breakpoint_path includes `../../`? They should all be canonical if I'm not mistaken.

**Comment by eidheim** [comment]
Using boost::filesystem::canonical should also solve this. It is what has been used other places as well. There might also be one less stat/GetFileInformationByHandle function call internally too by using boost::filesystem::canonical on breakpoint_path.

**Comment by milleniumbug** [comment]
The `breakpoint_path` is created by joining `file_spec.GetDirectory()` which already is non-canonical, with `file_spec.GetFilename()`. [Documentation of `.GetDirectory()` ](http://lldb.llvm.org/cpp_reference/html/classlldb_1_1SBFileSpec.html#a4a759130426d39154725bd5c9a99fd9c) isn't very helpful, so I reckon we have to sanitize the input anyway (...like one should do anyway)
