### ISSUE TITLE
Segmentation Fault while debugging

### ISSUE THREAD

**Issue by sappel34** [cppit/jucipp#225]
Opening the variable window (ctrl+shift+b) while debugging a simple program results in a segmentation fault under Arch linux with latest jucipp version. Core dump is downloadable here: http://dl.free.fr/kCttYyJMK

**Comment by eidheim** [comment]
Since it's a simple program, would you mind posting the source?

Also, trying to run lldb manually in a terminal and see if the segmentation fault occurs here as well would be an indication that the problem lies in lldb. lldb is not 100% yet, and usually the segmentation fault happens here, and not in juCi++.

**Comment by sappel34** [comment]
The "simple program" is yours ;) 

https://github.com/eidheim/Simple-Web-Server

http_examples.cpp

Breakpoint at line 72

I will check for lldb

**Comment by eidheim** [comment]
Removing `-O3` from Simple-Web-Server's CMakeLists.txt fixed the issue. Trying to figure out where the problem lies. Manual lldb worked at least for me.

**Comment by sappel34** [comment]
I confirm, manual lldb works here and the workaround works also :) Thanks!

**Comment by eidheim** [comment]
The segmentation fault happens in `lldb::SBValue::GetDescription`. Could not find a workaround. 

Reproducable with:
```sh
lldb ./Simple-Web-Server/build/debug/http_examples
b http_examples.cpp:72
thread select 2
frame select 4
frame variable
```
and this leads to a segmentation fault. Feel free to report the issue to the lldb developers:)

**Comment by sappel34** [comment]
Thanks. For reference: https://llvm.org/bugs/show_bug.cgi?id=27803

**Comment by eidheim** [comment]
Thank you, sorry I forgot to add that one also has to open `http://localhost:8080/info`.
