### ISSUE TITLE
Unable to type tab character in the middle/end of text

### ISSUE THREAD

**Issue by amit-jain-SBG** [cppit/jucipp#226]
Line indents instead.

**Comment by eidheim** [comment]
We should maybe have a preference item for this. But why are you doing this? Maybe use clang-format instead (control-shift-i)?

**Comment by amit-jain-SBG** [comment]
Simple usage:

int x = 2;<<\t>>// set to the smallest prime number

**Comment by eidheim** [comment]
I still would setup clang-format to do this for me actually. Doing such things manually feels a bit old-fashioned. See for instance http://clang.llvm.org/docs/ClangFormatStyleOptions.html and its AlignTrailingComments.
