### ISSUE TITLE
Code parser assumes release builds

### ISSUE THREAD

**Issue by amit-jain-SBG** [cppit/jucipp#227]
thus ignores anything inside asserts. This leads to incomplete refactoring often (e.g. variable rename doesn't rename instances inside assert).

For syntax purposes, either debug should be default, or this should be a preference. Or both.

**Comment by eidheim** [comment]
assert commands are typically defines that libclang struggle to parse. 

As long as lldb is not 100%, we should be using default build (we are not using release build) as default.

**Comment by eidheim** [comment]
Use for instance these options to always build debug:
```json
        "default_build_path": ".\/build",
        "debug_build_path": ".\/build",
        "cmake_command": "cmake -DCMAKE_BUILD_TYPE=Debug",
```
Then juCi++ will use the same binaries in both default and debug build, and compiles the sources only once no matter if you use project run or debug run.
