### ISSUE TITLE
Debug start/continue command leads to crash

### ISSUE THREAD

**Issue by amit-jain-SBG** [cppit/jucipp#228]
Where can I find a log to send you?

Thanks.

**Comment by eidheim** [comment]
Thank you, but could you elaborate? Does it happen every time? What OS are you using? You can also use lldb/gdb to generate a backtrace and paste it here.

Also, when it comes to lldb that juCi++ uses, try to reproduce the steps using lldb manually. On all occasions so far, the crash happens in lldb.

**Comment by amit-jain-SBG** [comment]
Start/continue without any options crashes.

gdb output for same scenario:
Starting program: /home/amit/seven-bridges-genomics/graph-alignment/build/debug/aligner 
warning: the debug information found in "/lib64/ld-2.19.so" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
PARSE ERROR:  
             Required arguments missing: reference, fastq, output

Brief USAGE: 
   /home/amit/seven-bridges-genomics/graph-alignment/build/debug/aligner 
                                        [--genotype_tags] [-g <.7bg>] [-G
                                        <.7bg>] -f <.fasta> [-v
                                        <.vcf/.bcf/.vcf.gz>] -q <.fastq>
                                        [-Q <.fastq>] -o <.bam> [-i] [-P
                                        <STR>] [-I <STR>] [-S <STR>] [-E
                                        <INT>] [-O <INT>] [-x <INT>] [-=
                                        <INT>] [--thread_buffer_size <INT>]
                                        [-t <INT>] [--debugging_tags]
                                        [--no_local_aligner] [-M] [-l
                                        <INT>] [-w <INT>] [-m <{0-20}>]
                                        [--hash_short_list <INT>]
                                        [--hash_table_size_log2 <{16-28}>]
                                        [--hash_block_step <{1-14}>]
                                        [--hash_block_size <{8-14}>] [-n
                                        <INT>] [-N <INT>] [--] [--version]
                                        [-h]

For complete USAGE and HELP type: 
   /home/amit/seven-bridges-genomics/graph-alignment/build/debug/aligner --help

[Inferior 1 (process 5532) exited with code 01]

**Comment by eidheim** [comment]
Try the same but with lldb instead of gdb please.

**Comment by eidheim** [comment]
Removing any optimisation flags like `-O3` when running debugging can also help work around lldb crashes. This is not a juCi++ issue however.

**Comment by eidheim** [comment]
Closing this, but feel free to reopen if it's not an lldb issue.
