### ISSUE TITLE
Look into CI for windows

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#231]
https://www.appveyor.com/

**Comment by eidheim** [comment]
https://github.com/Alexpux/MINGW-packages is using this. Looking into their setup might help understanding how it can work through MSYS2.

**Comment by zalox** [comment]
https://ci.appveyor.com/project/zalox/jucipp/build/1.0.14/job/feyh2bqiyi4hhegx

**Comment by eidheim** [comment]
@zalox I'm not sure if clang++ is usable on msys2 yet, g++ compilation of juCi++ on MSYS2 is more than enough.

**Comment by eidheim** [comment]
Unless clang++ is actually working? think I saw a build in the history that successfully built juCi++ with clang++ on MSYS2?

Is there supposed to be any output on the compilation and tests by the way? And, great work yet again!

**Comment by zalox** [comment]
I'm removing clang++ for now. I think https://github.com/zalox/jucipp/commit/c79e8866834566cd997f0cc71680c3d3f291fc79 fixes the output not showing up.
