### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by infgeoax** [cppit/jucipp#236]
![image](https://cloud.githubusercontent.com/assets/988067/15695053/abbf8cda-27e6-11e6-96ce-5be9f73ed942.png)

Any plans for creating an icon for juCi++? Would be nice.

**Comment by eidheim** [comment]
I can't draw at all, but it would be great if someone wants to create a suggestion for a juCi++ icon. Should probably be in svg format I guess.

**Comment by monsterjamp** [comment]
I'm not an artist either but I've messed around with Inkscape before and I can make concept icons/logos. Here's a few concept icons I made: 
- The first one is just a stylized font: 
  <img src="https://cloud.githubusercontent.com/assets/7116269/17122203/0cf0e16a-529f-11e6-8d39-f4df852805b0.png" width="100"/>

- The second one is the above icon in front of a feather (I could probably tweak it a bit more to make it look more "clean"): 
  <img src="https://cloud.githubusercontent.com/assets/7116269/17122204/0cf287c2-529f-11e6-84c7-975b09f7b775.png" width="125"/>

- And the last one is a more generic icon: 
<img src="https://cloud.githubusercontent.com/assets/7116269/17122205/0cfae278-529f-11e6-8719-d3a3f785e0ec.png" width="75"/>

@eidheim Do you like any of the designs above? Feel free to criticize :stuck_out_tongue:

**Comment by eidheim** [comment]
Thank you, I like the last one, since text in icons can mayve be problematic on some systems when the icons are small. But I should not decide I think, might be better if we vote on the various proposals:)

**Comment by underdoeg** [comment]
Where does the name jucipp come from, or what does it mean? Should probably be reflected in the icon as well somehow?

**Comment by eidheim** [comment]
@zalox should probably answer this, but my guess is that the name was partly chosen to be easy to google. From my point of view, juCi++ can have the following meanings:
  * You C++ or You Zip (Zip meaning the sound of a fast moving small object, that could represent the speed of the lightweight IDE)
  * You See (this is how most of us are pronouncing juCi++ in Norway, but as in one word)
  * Juicy (as in raw and smooth, or for instance in a programming context: simple IDE giving you a smooth and uncomplicated programming experience).

**Comment by zalox** [comment]
Hi,
Originally we named juCi++, cppit. It was meant to be like "just do it", but as "cpp it" instead. After giving the name some though I came to the conclusion that cppit was too tacky. Then someone said juicy++ and we instantly agreed.

**Comment by adobrich** [comment]
Here is another option:
![jucipp](https://cloud.githubusercontent.com/assets/445318/22243890/39ea345c-e221-11e6-8081-eb7b43d5d871.png)
Could probably use some tweaking...

**Comment by eidheim** [comment]
Really nice options! Both the icons above are great! Not sure if the icons should be svg, or is png ok? If png, we might need different scaled versions I guess?

**Comment by adobrich** [comment]
I have svg also.  I'll email them to you :)

**Comment by eidheim** [comment]
@adobrich Since no one else replied here, I decided to use your first proposed icon! Thank you again!

**Comment by eidheim** [comment]
Closing this since we now have an icon.
