### ISSUE TITLE
Supporting remote gdb/lldb-server (cross arm toolchain)

### ISSUE THREAD

**Issue by waterrice** [cppit/jucipp#238]
How to use jucipp with gdb client to connect to a remote gdbserver (cross arm toolchain)?

**Comment by milleniumbug** [comment]
juCi++ uses lldb as a debugger, so if lldb supports gdb remote protocol, remote debugging should be possible to implement.

**Comment by eidheim** [comment]
Is there an lldb server? I'm quite happy with the choice of lldb for debugging, even though we were maybe a bit early in using its library. Even so, as a result, we have been part of improving lldb through reporting various issues.

Now, creating a lldb server using the lldb library might be a good idea, maybe through websockets with the possibility of encryption using WSS at the same time. Additionally, one could create a debugging web-interface to the server without the need of a intermediate service. This should be doable through Simple-WebSocket-Server, although this library requires boost to be installed (or statically linked). I don't have time for this, but feel free to look around, or even create such a server. Worst case, I can get some students to work on this next spring:) This server would of course be a separate project, not part of juCi++. 

One question though, how are files handled through the gdb server? Are they uploaded, or are they reached through a different service? Or maybe only local files on the client side is considered?

**Comment by waterrice** [comment]
> One question though, how are source files handled through the gdb server? Are they uploaded, or are they reached through a different service? Or maybe only local files on the client side is considered?

Source files are only on the client side (the PC that juCi++ is running on). The target don't have any toolchain.

I'm migrating our applications for an embedded system from makefile to CMake and I'm quite happy with CMake for cross compilation, and juCi++ as IDE (alternative to Netbeans C++, that we've been already using for last 6 years). Thanks juCi++, awesome work!

**Comment by eidheim** [comment]
Actually there is a lldb-server: http://lldb.llvm.org/remote.html. You can probably play around with debug_clang.cc to get this to work. That is, the lldb library should support this as well. Maybe we can add a server:port parameter to the menu item Set Run Arguments. That, and a few changes in debug_clang.* should be enough I think.

I would suggest lldb anyway in the future, since it is faster and better implemented than gdb. And of course: it has a library, with a decent API although with lacking documentation.

**Comment by eidheim** [comment]
@waterrice I took the liberty to change the issue title.

**Comment by eidheim** [comment]
Based on http://lldb.llvm.org/remote.html it seems gdb-remote protocol is used in lldb-server as well.

**Comment by eidheim** [comment]
@waterrice Could you have a look at http://lldb.llvm.org/remote.html and see if you manage to remote debug your application through the lldb command line? I have no experience with this, but the commands you would use will be of great help implementing this. You can use the remote-gdb-server (see `platform list`) plugin to connect to gdbserver. 

It seems lldbserver has extra functionality. Is it possible for you to use lldb server instead of gdbserver? lldbserver is statically linked by the way, so it should be installable on most devices. Asking since we have to decide to support gdbserver additionally to lldbserver, or not.

**Comment by waterrice** [comment]
I will take a try this weekend. After some research, it seemed that I have to build lldb-server on the target by my self. 

We're using crosstool-ng https://github.com/crosstool-ng/crosstool-ng as the toolchain with buildroot https://buildroot.org/  to build up our ARM9 system. By default, I don't see the llvm, clang and lldb-server on the target package list.

Thanks for your guide, I will post back with results.

**Comment by eidheim** [comment]
Thank you, and no worries, we can go with gdb-server and lldb's remote-gdb-server plugin for now.

**Comment by eidheim** [comment]
@waterrice Just to be sure, you compile the executable on the client machine right? That is the one running juCi++, and lldb through the remote-gdb-server plugin should transfer the executable to the target device and of course run it there in gdb-server? And you have setup CMakeLists.txt (http://www.vtk.org/Wiki/CMake_Cross_Compiling) to do the compilation for this target I guess. Finally, is this the most common use case with regards to cross compiling, or should we consider other use cases as well?

**Comment by waterrice** [comment]
> Just to be sure, you compile the executable on the client machine right? That is the one running juCi++
Yes.

>  And you have setup CMakeLists.txt (http://www.vtk.org/Wiki/CMake_Cross_Compiling) to do the compilation for this target I guess. Finally, is this the most common use case with regards to cross compiling
Yes. Buildroot do produce a ready make CMake toolchain setting file for us.
<Buildroot Directory after build>/output/host/usr/share/buildroot/toolchainfile.cmake

And we've bean remote debugging with gdbserver (running in ther target, with the application binary transferred manually by scp) for times. juCi++ has awesome support for CMake so we intended to make an IDE switch, at least gradually, from Netbeans C++.

This is the first time I am using lldb and the remote-gdb-server plugin, so I need some setting up and getting familiar with terminologies. I will post back with the result.

Thank you @eidheim for clarify for me.

**Comment by eidheim** [comment]
Thank you. I think this should be very doable in the coming 1-2 weeks.

**Comment by eidheim** [comment]
![debug](https://cloud.githubusercontent.com/assets/5269318/15894761/f9efaefc-2d87-11e6-9145-1297fb0ac127.png)

The options for remote debugging will most likely be added where you see "Not yet implemented" in the image above.

**Comment by eidheim** [comment]
Feel free to try out pull request #241. Sadly, it seems like you have to compile lldb anyway. The gdbserver and lldb is not 100% compatible it seems. For some reason, you need to run lldb's gdbserver on the device. I don't 100% understand what they have done, but it seems they have implemented their own gdbserver.

Have not yet implemented:
* passing arguments to the executable on the device
* passing environment variables to the executable on the device
* set the path where the executable should be run from on the device

**Comment by waterrice** [comment]
Thanks @eidheim, I promise i will try out all of your suggestions and juCi++ new remote debugging feature. This is my first time with lldb, llvm so everything related are new for me.

**Comment by waterrice** [comment]
Ah, porting new package for target platform are no problem for my team, so I will try lldb with current gdbserver, but will compile lldbserver as well.

**Comment by eidheim** [comment]
![debug](https://cloud.githubusercontent.com/assets/5269318/15961748/c3070eb4-2f06-11e6-8de4-55a0012f905e.png)

Study the above image (latest commit from #241), it shows how one does remote debugging. To my surprise, arguments, environment variables and executable path are all supported:)

Its a bit confusing, but to run the supported lldbserver you run the following command on the remote device:
`lldb-server gdbserver *:1234`
Replace `*` to specify which IP(s) should be allowed to connect, and 1234 is the port. The command `lldb-server gdbserver` may be slightly different depending on the OS you are on. The image above is created in Debian Testing.
