### ISSUE TITLE
Fixes needed for continuous integration

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#242]
As mentioned in #241.

### Todo
- [x] ~~lldb is not installed on the archlinux docker image that travis is using.~~
- [x] `make test`, is only executing `make` on msys2

**Comment by zalox** [comment]
@eidheim I'll look at this, this evening, feel free to amend list items :)

**Comment by zalox** [comment]
@eidheim https://travis-ci.org/cppit/jucipp/jobs/136135405 The lldb in arch seems to be working now.

**Comment by eidheim** [comment]
I saw, great!

**Comment by eidheim** [comment]
@zalox Also have a look at how scan-build should be run (I think): https://github.com/cppit/jucipp/pull/220#issuecomment-220900824.

**Comment by zalox** [comment]
@eidheim Is this correct behaviour? https://ci.appveyor.com/project/zalox/jucipp-6hwdu

**Comment by eidheim** [comment]
tests are working on my MSYS2, so I guess no:)

**Comment by eidheim** [comment]
@zalox You might also want to add libgit2(-dev) to the various dockers and MSYS2 builds in preparation for https://github.com/eidheim/jucipp/tree/git! Feel free to try it out. It's not done yet, probably need a week or so, but source diffs based on the git repository works quite well in standard use cases. I already use it:)

**Comment by zalox** [comment]
Cool, I will look at it tonight. You can create your own user account on travis to run your fork without pull requesting btw.

**Comment by eidheim** [comment]
This build failed on master: https://travis-ci.org/cppit/jucipp/builds/137490391

I'll look into travis accounts later so I don't have to hazzle you on such issues. That is, probably just a rebuild needed.
