### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by vadimgit** [cppit/jucipp#243]
cant build current brunch..  Looks like default constructor is not generated automatically for clang::Cursor
because this one was declared explicitly : 
```C++
Cursor(const CXCursor &cx_cursor) : cx_cursor(cx_cursor) {}
```

or do I do something wrong?

**Comment by eidheim** [comment]
Did you do `git clone --recursive https://github.com/cppit/jucipp`? The libclangmm module is probably updated since you last cloned jucipp, and thus git pull is not enough, one has to get the new submodules as well.

**Comment by vadimgit** [comment]
Oh. Thanks. 
Did not commit sub module's changes after fetching from upstream.
Can be closed.

**Comment by eidheim** [comment]
Happy to hear it helped, closing then:)
