### ISSUE TITLE
Make background pattern optional

### ISSUE THREAD

**Issue by ff2000** [cppit/jucipp#245]
I can't see the cursor because it has the same colour as the grid. Also I had an issue in the past (gtk+-update broke gtksourceview) with background being rendered in default widget bg-color resulting in unreadable text.

In general I find the pattern distracting. So I would like to see an option to disable it.

**Comment by eidheim** [comment]
You can update the source-style you are using. Set the background of background-pattern equal to the text-background.

**Comment by ff2000** [comment]
Thx, worked!
