### ISSUE TITLE
completion popup misplaced

### ISSUE THREAD

**Issue by ff2000** [cppit/jucipp#246]
For me the popup shows up at the top left corner of my screen and not at the cursor position. Tooltips also show up at the left top corner after a completion popped up, but after some time they move to the expected position (which is weird ;)).

I am using awesomeWM. The issue is not related to window tiling because it also happens with floating windows.
I use gtksourceview-3.20.1, gtksourceviewmm-3.18.0, gtk+-3.20.2 and gtkmm-3.18.1.

**Comment by eidheim** [comment]
Are you using Wayland or X? We fixed some Wayland issues at least some weeks back.

**Comment by ff2000** [comment]
awesome is still on X, so no - I don't use wayland.

**Comment by eidheim** [comment]
The issue is that the tooltips are briefly positioned at top left corner before getting correctly positioned near cursor/mouse pointer?

**Comment by ff2000** [comment]
On Fri, 17 Jun 2016 00:53:52 -0700, Ole Christian Eidheim <notifications@github.com> wrote:
> The issue is that the tooltips are briefly positioned at top left corner before getting correctly positioned near cursor/mouse pointer?

No. I mentioned tooltips (e.g. those showing an error when hovering an underlined expression) because it looked like a weird side effect caused by the general and never correct placement of source completion popup, which always is placed at top left corner, and I thought it might help to get to the root of both issues. But probably I was wrong.
But now that I try this again: There seem to be two tooltips! One that shows error messages (e.g. "unknown type name XYZxxx") and another one that shows semantic type info. The one showing the type always comes up in the top left corner. The completion popup (offering candidates for completion like function or type names) also always comes up in the top left corner.
If I open jucipp, open a file and type an errorness expression, wait for the curly underline, then hover the text the tooltip is positioned as expected near the cursor. As soon as the completion pops up this tooltip also shows up in the top left corner. Moving the mouse away and hovering the marked text again it magically gets positioned correctly again (near the cursor).

I hope that made my issues more clear.

**Comment by eidheim** [comment]
Thank you, I'll give awesomeWM a try. What Linux OS are you using?

**Comment by ff2000** [comment]
On Fri, 17 Jun 2016 01:25:09 -0700, Ole Christian Eidheim <notifications@github.com> wrote:
> Thank you, I'll give awesomeWM a try. What Linux OS are you using?

I am on Gentoo linux.

And it seems this is not related to awesome. I just fired up qtile which showed the same issue. Even fluxbox behaves as described above.
Any hint where I could look?

I also tried it with wayland now (using sway) and there no tooltips show up at all. The completion shows up at the top left corner of the jucipp window.

**Comment by eidheim** [comment]
Sorry, I do not know the source of the problem yet. Might it be related to Gentoo? You could try gtk3-demo and see if the various demos behave ordinarily. Especially the demos with popup windows, like popover and such. 

Could you check if the position of Debug->set run parameters->options popover is correct?

**Comment by eidheim** [comment]
Just tried Awesome on Debian Testing and there were no issues.

**Comment by eidheim** [comment]
Could this be related: https://bugzilla.gnome.org/show_bug.cgi?id=760253?

**Comment by eidheim** [comment]
From the bug report above:
"Same configuration in Gnome-Shell, Openbox or XFCE does not have this problem."

Would you mind trying one of those?

**Comment by ff2000** [comment]
openbox also doesn't work for me. gtk3-demo is not installed, but as gtk3-popovers work as well as tooltips in other applications, I think the issue I have with jucipp is "special". I have built firefox against gtk3 and here everything works as perfectly: tooltips as well as the omnibar-popup (URL suggestions) are positioned as expected. I also have no issues with other gnome apps like dconf-editor, gnome-system-monitor and nautilus.

BTW: the context menu in jucipp also works fine, real issues only are caused by completion popup and type tooltip.

**Comment by zalox** [comment]
I haven't had any issues related to awesome wm. I've been using it since development of juCi++ started. I've been using debian stable/testing and arch.

**Comment by eidheim** [comment]
I tried install Gentoo, but I really do not have time for such a manual install. @zalox you might feel right at home with your Arch Linux experience:) Would be nice if someone could verify this issue.

**Comment by zalox** [comment]
I'm away until Monday, I might have time to look at it then.

**Comment by eidheim** [comment]
@zalox Great!

@ff2000 Feel free to play around with https://github.com/cppit/jucipp/blob/master/src/tooltips.cc#L107 and maybe change the Window type hint in: https://github.com/cppit/jucipp/blob/master/src/tooltips.cc#L56
Also make sure you clone the latest https://github.com/cppit/jucipp.

**Comment by ff2000** [comment]
Sry for being a Gtk noob ;)
Diving into te docs I read this line:

```
Window managers are free to ignore this; most window managers ignore requests for initial window positions (instead using a user-defined placement algorithm) and honor requests after the window has already been shown.Window managers are free to ignore this; most window managers ignore requests for initial window positions (instead using a user-defined placement algorithm) and honor requests after the window has already been shown.
```

And in fact calling `window->show_all()` before `window->move()` in line 107 fixes the issue for Tooltips. I am sure there is a similar fix for completion popup. And - yeah :) - swapping LL 102 and 103 in selectiondialog.cc fixes also the completion popup :)

**Comment by eidheim** [comment]
Splendid! I'll look into it Tomorrow morning, and most likely merge the fix to master. Not sure why I decided to place move before show_all, but I'll double check that it has no consequence for other platforms just to be sure. Thank you:)

**Comment by ff2000** [comment]
Tooltips::show requires some more thought than just moving some lines, that's why I didn't create a PR ;)
And it's interesting that it seems to work for everyone else. Possibly related to some parts in the graphics stack. I think I came across similar bug-reports where the culprit was the closed nvidia-drivers. I am using latest intel-drivers, but probably there is also some weird interaction going on... Or most binary distros ship some patched versions of involved packages.

**Comment by eidheim** [comment]
Should work now on all platforms. Wayland positioning did not work unless I also added move before show_all. Thank you again!

**Comment by eidheim** [comment]
@ff2000 Would you mind double check if cppit master also fixes the tooltip/dialog placement? Just curious if adding `move` before and after `show_all` is ok with your window manager:)

**Comment by ff2000** [comment]
Yes, for X this issue is fixed. But in sway (wayland) the completion popup still comes up in the top left corner of the window (not screen). The position where it should get moved is correct (verified via cout), but I get a gdk warning:
```
Gdk-WARNING **: No grabbed seat found, using the default one in order to map popup window 0x1911b80. You may find oddities ahead, gdk_seat_grab() should be used to simultaneously grab input and show this popup.
```
Tooltips work fine in sway.

**Comment by eidheim** [comment]
@ff2000 I connected to the realize signal and placed the moves there. Now it works for Wayland/X/OS X/MSYS2 on my side without any hacks. Would you mind test the latest cppit/jucipp master again:)?

The warning is something that gtk needs to fix on their side. My guess is that it's fixed on gtk3.22 when it comes. Wayland support is pretty good in gtk, but not 100% yet.

**Comment by ff2000** [comment]
@eidheim yes, fixes the issue - and it still works on X, too :)
Nevertheless... I get a flickering tooltip under wayland ^^ For sure not your fault, but I didn't think that could ever happen because of design. On X with compton it's a smooth transition.

One could get rid of the tooltip: Copy kdevelop ;) It uses a tree with collapsable entries which hide the details about the symbol:

![Kdevelop auto completion](https://userbase.kde.org/File:Kdevelop-43.png)

**Comment by eidheim** [comment]
Thank you yet again:)

My worry about tooltips such as the one in KDevelop is that one gets highly dependent on using the mouse pointer. As it is now, in juCi++, there is no need to use the mouse at all when working in the source view, including getting tooltips (which can be shown by moving the text cursor). Of course, we could extend the tooltips to include more information and clickable links in the future. One could then maybe extend the tooltip to hide if the mouse pointer does not reach the tooltip within a second or two. But still, we already have goto declaration/implementation and show uses through key bindings, and adding links to the tooltip would mostly be useful to new users of juCi++. Ideas like this is highly appreciated though:)

**Comment by ff2000** [comment]
On Sun, 19 Jun 2016 00:45:32 -0700, Ole Christian Eidheim <notifications@github.com> wrote:
> Thank you yet again:)
> 
> My worry about tooltips such as the one in KDevelop is that one gets highly dependent on using the mouse pointer. As it is now, in juCi++, there is no need to use the mouse at all when working in the source view, including getting tooltips (which can be shown by moving the text cursor). Of course, we could extend the tooltips to include more information and clickable links in the future. One could then maybe extend the tooltip to hide if the mouse pointer does not reach the tooltip within a second or two. But still, we already have goto declaration/implementation and show uses through key bindings, and adding links to the tooltip would mostly be useful to new users of juCi++. Ideas like this is highly appreciated though:)

The suggestion was not to copy kdevelop's verbosity but to hide the tooltip as it's useful mostly for new users to a certain API ;)
AFAIR one does not have to use the mouse to expand a suggestion, it's possible with <SPACE> as well (at least it was when I used it the last time).

If there was a feature I would like to see copied it would be kdevelop's DUChain - persistent usage of definitions for the whole project. As it is now juci will allow "go to usage" and "got to implementation" (and probably more) only for open files. If this is within the scope of juci I can open a new issue :)

**Comment by eidheim** [comment]
Feel free to open an issue on this. However, it is a problem that has no apparent good solution. Background parsing of the sources would be required, and if the build is altered, a whole new background parsing would be needed. In large projects, this would take hours to do properly... It also goes against C/C++ and libclang with its implementation file by file parsing (and compilation). It is simpler to implement for other languages, but not sure it is a good idea to implement for a complex language like C++, unless one is ok with shortcuts and worse C/C++ language support. It might be that llvm finds a solution for this in the future though, but I have my doubts as there might be no good way to do this.
