### ISSUE TITLE
Moving the mouse in SourceView results in high CPU usage

### ISSUE THREAD

**Issue by ff2000** [cppit/jucipp#247]
For me it uses up to 100% of one (virtual) core. I first thought it was due to continuously re-connecting in motion_notify_event (source.cc:392), but even after commenting out all the code CPU usage doesn't change. This is really bad for my laptop battery ;)
I could not find another place where juci catches mouse moves, so could this be an issue in GtkSourceView?

**Comment by eidheim** [comment]
I saw the same thing, or cpu peaks to around 70% some times, and the problem might be in either gtkscrollview or gtktextview. I'll try later to override the `on_motion_notify_event` in `source.cc` and see if I can stop the peaks.

To improve battery life, I would maybe first turn off the source map in preferences. Maybe turn off the git integration as well (if you are using #244 ), not sure how much power that one consumes. If you would have a look, it would be much appreciated:)

**Comment by ff2000** [comment]
On Tue, 21 Jun 2016 00:28:59 -0700, Ole Christian Eidheim <notifications@github.com> wrote:
> To improve battery life, I would maybe first turn off the source map in preferences. Maybe turn off the git integration as well (if you are using #244 ), not sure how much power that one consumes. If you would have a look, it would be much appreciated:)
source.show_map is set to false already.
And I use master ;)

**Comment by eidheim** [comment]
I managed to turn off all mouse motion events, and there were still a somewhat higher cpu usage when moving the mouse pointer around. Saw the same effect in gedit as well.

**Comment by ff2000** [comment]
So this is an issue in gtksourceview? At least moving the mouse around in the juci-terminal does not show noticeable CPU-Usage.

**Comment by eidheim** [comment]
I saw the same effect when moving the mouse pointer in the terminal view as well, when it had some hundred lines in it. Did not see the effect in firefox though, so the issue might be in gtktextview (doubt firefox is using textview to show web pages, but they might be using gtkscrolledwindow).

**Comment by ff2000** [comment]
Ah, OK, my terminal only had 5 lines when I did the test xD

**Comment by eidheim** [comment]
Since you maybe build glib and gtk yourself, maybe look at the build options here: https://github.com/GNOME/glib/blob/master/docs/macros.txt. Especially `--enable-debug=no` may improve performance and memory use.

**Comment by ff2000** [comment]
On Mon, 27 Jun 2016 04:32:10 -0700, Ole Christian Eidheim <notifications@github.com> wrote:
> Since you maybe build glib and gtk yourself, maybe look at the build options here: https://github.com/GNOME/glib/blob/master/docs/macros.txt. Especially `--enable-debug=no` may improve performance and memory use. 

It's already built with debugging disabled. I have -ggdb in my C[XX]FLAGS but split debugging symbols out of the binaries, so runtime performance shouldn't be bad.

**Comment by eidheim** [comment]
I'm taking the liberty to close this issue, as it is not something we can fix in juCi++ I think. Feel free to report the issue to gtk however.
