### ISSUE TITLE
Freeze in debug mode

### ISSUE THREAD

**Issue by sv1990** [cppit/jucipp#261]
Everytime when I'm starting a debug run juci recompiles my code and then freezes before executing. 
The task manager is not showing any extraordinary CPU usage.
I'm using juci on Manjaro-stable. Please let me know if I can provide more information on that issue.

**Comment by eidheim** [comment]
On some platforms you have to place juCi++ in the foreground (as in not running it in the background in a shell) before debug can start. This is an lldb issue I think.

**Comment by sv1990** [comment]
Thanks! That solves my problem.
