### ISSUE TITLE
juci++ Ubuntu 16.04 empty window

### ISSUE THREAD

**Issue by matsbror** [cppit/jucipp#264]
I just did a clean install according to the wiki on an Ubuntu 16.04 system. When I started juCi++, the window is completely blank and I have clue what to do next.
![juci _001](https://cloud.githubusercontent.com/assets/10210145/17132571/a47a1172-5322-11e6-9f48-687972ac9c59.png)

**Comment by eidheim** [comment]
Either create a new c++ project in the file menu, or open an existing cmake project.

**Comment by matsbror** [comment]
The issue is, there is no file menu!

**Comment by eidheim** [comment]
Ubuntu has the application menu on the top of the screen. It appears when you focus the juci window.

**Comment by eidheim** [comment]
Or when you place the mouse on top of the screen:)

**Comment by matsbror** [comment]
Silly me (not coming from a mac world...)
