### ISSUE TITLE
Error when building on Ubuntu 14.04

### ISSUE THREAD

**Issue by matsbror** [cppit/jucipp#265]
I am using gcc 5.3 on Ubuntu 14.04 and gets the following errorÖ
In file included from /home/mats/src/jucipp/src/directories.h:13:0,
                 from /home/mats/src/jucipp/src/ctags.cc:6:
/home/mats/src/jucipp/src/git.h:41:61: error: ‘git_diff_hunk’ does not name a type
       static int hunk_cb(const git_diff_delta *delta, const git_diff_hunk *hunk
                                                             ^
/home/mats/src/jucipp/src/git.h:42:61: error: ‘git_diff_hunk’ does not name a type
       static int line_cb(const git_diff_delta *delta, const git_diff_hunk *hunk
                                                             ^
/home/mats/src/jucipp/src/git.h:42:88: error: ‘git_diff_line’ does not name a type
 ne_cb(const git_diff_delta *delta, const git_diff_hunk *hunk, const git_diff_li

**Comment by eidheim** [comment]
Ubuntu 14 is no longer supported sadly, since its packages are quite old (older than debian stable), and is missing support for too many features.

**Comment by weegreenblobbie** [comment]
Was there a version that worked in the past?  I want to debug my program on 14.04.

**Comment by eidheim** [comment]
Have a look at before https://github.com/cppit/jucipp/commit/61319b9a6b34915bf326eb3d7364fe92a52bbb1d

**Comment by weegreenblobbie** [comment]
In case someone off the intertubes is in a bind and really really wants to run jucipp on 14.04:

# building juci++ on Ubuntu 14.04

# install newer libgtkmm-dev

sudo add-apt-repository ppa:gnome3-team/gnome3
sudo add-apt-repository ppa:gnome3-team/gnome3-staging
sudo apt-get update
sudo apt-get upgrade libgtkmm-3.0-dev

# install newer libgit2

sudo add-apt-repository ppa:kronoss/libgit2
sudo apt-get update
sudo apt-get install libgit2-dev

# checkout jucipp from git
git clone https://github.com/cppit/jucipp
cd jucipp

# switch to older commit and update submodules

git checkout d09810f992

git submodule update --init --recursive

# configure cmake build

mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER=g++ ..
make -j 4

# launch juci
src/juci

**Comment by eidheim** [comment]
Closing this as Ubuntu 14.04 is quite old now.
