### ISSUE TITLE
Ubuntu 15.10 Failed Build

### ISSUE THREAD

**Issue by madisodr** [cppit/jucipp#266]
Building on Ubuntu 15.10. Same issue as detailed  [here](https://github.com/cppit/jucipp/issues/253
).

I was able to get it to build by changing the **Gio::FileMonitorFlags::FILE_MONITOR_WATCH_MOVES** to **Gio::FileMonitorFlags::FILE_MONITOR_SEND_MOVED**

In the Ubuntu library for ([glibmm](http://packages.ubuntu.com/wily/libglibmm-2.4-1v5)), looking at the source, in file.h where it should define FILE_MONITOR_WATCH_MOVES, the enum doesn't contain it. 

```c++
enum FileMonitorFlags
{
  FILE_MONITOR_NONE = 0x0
  FILE_MONITOR_WATCH_MOUNTS = (1 << 0),
  FILE_MONITOR_SEND_MOVED = (1 << 1),
  FILE_MONITOR_WATCH_HARD_LINKS = (1 << 2)
};
```

Which since it is 2.44 it should contain that declaration but it doesn't. 
Unless FILE_MONITOR_WATCH_MOVES was implemented after version 2.44.0, the version that installs by default with Ubuntu15.10.

**Comment by eidheim** [comment]
Thank you. It might be a documentation issue here for instance: https://developer.gnome.org/glibmm/stable/group__giommEnums.html#ga469f795e9a4dddb2421c0e5568be6649. We might fix this by figuring out which version of glibmm really introduced FILE_MONITOR_WATCH_MOVES.
