### ISSUE TITLE
Linking error on Ubuntu 15.10

### ISSUE THREAD

**Issue by ebaratte** [cppit/jucipp#267]
Building fails on Ubuntu 15.10 at linking stage:

`CMakeFiles/juci.dir/dialogs.cc.o:dialogs.cc:function Dialog::Message::Message(std::string const&): error: undefined reference to 'Glib::ustring::ustring(std::string const&)'
CMakeFiles/juci.dir/dialogs.cc.o:dialogs.cc:function Dialog::Message::Message(std::string const&): error: undefined reference to 'Glib::ustring::ustring(std::string const&)'
CMakeFiles/juci.dir/dialogs.cc.o:dialogs.cc:function Dialog::gtk_dialog(boost::filesystem::path const&, std::string const&, std::vector<std::pair<std::string, Gtk::ResponseType>, std::allocator<std::pair<std::string, Gtk::ResponseType> > > const&, Gtk::FileChooserAction): error: undefined reference to 'Glib::ustring::ustring(std::string const&)'
CMakeFiles/juci.dir/dialogs.cc.o:dialogs.cc:function Dialog::gtk_dialog(boost::filesystem::path const&, std::string const&, std::vector<std::pair<std::string, Gtk::ResponseType>, std::allocator<std::pair<std::string, Gtk::ResponseType> > > const&, Gtk::FileChooserAction): error: undefined reference to 'Glib::ustring::ustring(std::string const&)'
CMakeFiles/juci.dir/dialogs.cc.o:dialogs.cc:function Dialog::gtk_dialog(boost::filesystem::path const&, std::string const&, std::vector<std::pair<std::string, Gtk::ResponseType>, std::allocator<std::pair<std::string, Gtk::ResponseType> > > const&, Gtk::FileChooserAction): error: undefined reference to 'Gtk::FileChooser::get_filename() const'
CMakeFiles/juci.dir/directories.cc.o:directories.cc:function Directories::Directories(): error: undefined reference to 'Gtk::CssProvider::load_from_data(std::string const&)'
CMakeFiles/juci.dir/directories.cc.o:directories.cc:function Directories::Directories(): error: undefined reference to 'Gtk::CssProvider::load_from_data(std::string const&)'
CMakeFiles/juci.dir/directories.cc.o:directories.cc:function void Gtk::TreeRow::set_value<std::string>(Gtk::TreeModelColumn<std::string> const&, std::string const&) const: error: undefined reference to 'Glib::Value<std::string>::set(std::string const&)'
CMakeFiles/juci.dir/info.cc.o:info.cc:function Info::Info(): error: undefined reference to 'Gtk::CssProvider::load_from_data(std::string const&)'
CMakeFiles/juci.dir/info.cc.o:info.cc:function Info::Info(): error: undefined reference to 'Gtk::CssProvider::load_from_data(std::string const&)'
CMakeFiles/juci.dir/juci.cc.o:juci.cc:function Application::on_command_line(Glib::RefPtr<Gio::ApplicationCommandLine> const&): error: undefined reference to 'Glib::set_prgname(std::string const&)'
CMakeFiles/juci.dir/project.cc.o:project.cc:function Project::Clang::debug_show_variables()::{lambda(std::string const&)#3}::operator()(std::string const&) const::{lambda()#1}::operator()() const: error: undefined reference to 'Glib::ustring::replace(Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >, Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >, char const*)'
CMakeFiles/juci.dir/project.cc.o:project.cc:function Project::Clang::debug_show_variables()::{lambda(std::string const&)#3}::operator()(std::string const&) const::{lambda()#1}::operator()() const: error: undefined reference to 'Glib::ustring::validate(Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >&)'
CMakeFiles/juci.dir/selectiondialog.cc.o:selectiondialog.cc:function SelectionDialogBase::ListViewText::append(std::string const&): error: undefined reference to 'Glib::Value<std::string>::set(std::string const&)'
CMakeFiles/juci.dir/selectiondialog.cc.o:selectiondialog.cc:function SelectionDialogBase::add_row(std::string const&): error: undefined reference to 'Glib::Value<std::string>::set(std::string const&)'
CMakeFiles/juci.dir/terminal.cc.o:terminal.cc:function std::_Function_handler<void (), Terminal::async_print(unsigned long, std::string const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&): error: undefined reference to 'Glib::ustring::replace(Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >, Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >, char const*)'
CMakeFiles/juci.dir/terminal.cc.o:terminal.cc:function std::_Function_handler<void (), Terminal::async_print(unsigned long, std::string const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&): error: undefined reference to 'Glib::ustring::validate(Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >&)'
CMakeFiles/juci.dir/terminal.cc.o:terminal.cc:function std::_Function_handler<void (char const*, unsigned long), Terminal::process(std::istream&, std::ostream&, std::string const&, boost::filesystem::path const&)::{lambda(char const*, unsigned long)#1}>::_M_invoke(std::_Any_data const&, char const*, unsigned long): error: undefined reference to 'Glib::ustring::replace(Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >, Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >, char const*)'
CMakeFiles/juci.dir/terminal.cc.o:terminal.cc:function std::_Function_handler<void (char const*, unsigned long), Terminal::process(std::istream&, std::ostream&, std::string const&, boost::filesystem::path const&)::{lambda(char const*, unsigned long)#1}>::_M_invoke(std::_Any_data const&, char const*, unsigned long): error: undefined reference to 'Glib::ustring::validate(Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >&)'
CMakeFiles/juci.dir/terminal.cc.o:terminal.cc:function Terminal::print(std::string const&, bool): error: undefined reference to 'Glib::ustring::replace(Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >, Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >, char const*)'
CMakeFiles/juci.dir/terminal.cc.o:terminal.cc:function Terminal::print(std::string const&, bool): error: undefined reference to 'Glib::ustring::validate(Glib::ustring_Iterator<__gnu_cxx::__normal_iterator<char*, std::string> >&)'
CMakeFiles/project_shared.dir/source.cc.o:source.cc:function Source::guess_language(boost::filesystem::path const&): error: undefined reference to 'Gio::content_type_guess(std::string const&, unsigned char const*, unsigned long, bool&)'
CMakeFiles/project_shared.dir/source.cc.o:source.cc:function Source::guess_language(boost::filesystem::path const&): error: undefined reference to 'Gsv::LanguageManager::guess_language(std::string const&, std::string const&)'
CMakeFiles/project_shared.dir/source.cc.o:source.cc:function Source::guess_language(boost::filesystem::path const&): error: undefined reference to 'Gsv::LanguageManager::get_language(std::string const&)'
CMakeFiles/project_shared.dir/source.cc.o:source.cc:function Source::guess_language(boost::filesystem::path const&): error: undefined reference to 'Gsv::LanguageManager::get_language(std::string const&)'
CMakeFiles/project_shared.dir/source.cc.o:source.cc:function Source::View::configure(): error: undefined reference to 'Gsv::StyleSchemeManager::prepend_search_path(std::string const&)'
CMakeFiles/project_shared.dir/source.cc.o:source.cc:function Source::View::configure(): error: undefined reference to 'Gsv::StyleSchemeManager::get_scheme(std::string const&)'
CMakeFiles/project_shared.dir/source.cc.o:source.cc:function Source::GenericView::GenericView(boost::filesystem::path const&, Glib::RefPtr<Gsv::Language>): error: undefined reference to 'Gsv::LanguageManager::get_search_path() const'
CMakeFiles/project_shared.dir/source.cc.o:source.cc:function Source::GenericView::GenericView(boost::filesystem::path const&, Glib::RefPtr<Gsv::Language>): error: undefined reference to 'Gsv::LanguageManager::get_search_path() const'
CMakeFiles/project_shared.dir/source_clang.cc.o:source_clang.cc:function Source::ClangViewParse::show_type_tooltips(Gdk::Rectangle const&)::{lambda()#1}::operator()() const: error: undefined reference to 'Glib::ustring::operator=(std::string const&)'
collect2: error: ld returned 1 exit status
`

Note: the output of cmake is:

`
etienne@etienne-dev:build (master *)$ cmake ..
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/local/bin/cc
-- Check for working C compiler: /usr/local/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibClang: /usr/lib/llvm-3.6/lib/libclang.so  
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found ASPELL: /usr/lib/x86_64-linux-gnu/libaspell.so  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Checking for module 'gtkmm-3.0'
--   Found gtkmm-3.0, version 3.16.0
-- Checking for module 'gtksourceviewmm-3.0'
--   Found gtksourceviewmm-3.0, version 3.12.0
-- Checking for module 'libgit2'
--   Found libgit2, version 0.22.2
-- Could NOT find plantuml (missing:  PLANTUML_JARFILE) 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.9.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/etienne/jucipp/build
`

**Comment by eidheim** [comment]
I see you are using `/usr/local/bin/c++` to compile. Is this clang++? You need to compile with g++. Hopefully this will solve the issue.

**Comment by eidheim** [comment]
That is, delete the build directory then:
```sh
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER=g++ ..
make
sudo make install
```

**Comment by ebaratte** [comment]
I was using g++-4.9.3. Compiling was successul with g++-5

**Comment by eidheim** [comment]
Great, it probably mean that your libraries installed in Ubuntu 15 is compiled with a g++-5 compiler, and one is getting ABI incompatibilities when trying to compile with g++4.9.
