### ISSUE TITLE
Does not run on windows

### ISSUE THREAD

**Issue by d3rrial** [cppit/jucipp#269]
I've been following the installation guide on windows, everything builds fine, no issues, but when I start the compiled juci.exe from within mingw64, it just immediately returns with exit code 127 and I'm unable to find out why.

Is this something known that I have overlooked?

Regards

**Comment by eidheim** [comment]
Thank you, have not tested on MSYS2 in a while actually, other than the AppVeyor tests. It seems that gtk(mm) is broken on MSYS2. The following gtkmm example exits in a similar manner as well on MSYS2: https://github.com/ntnu-ifud1048/gtkmm-example.

**Comment by eidheim** [comment]
It might be related to this issue: https://github.com/Alexpux/MINGW-packages/issues/1685

**Comment by d3rrial** [comment]
That's probably it, yes.

**Comment by eidheim** [comment]
Fixed now at MSYS2
