### ISSUE TITLE
Indentation on newline

### ISSUE THREAD

**Issue by d3rrial** [cppit/jucipp#276]
When I randomly click at the end of some line in juCi++ and hit the Return key, a newline is created, but there is no indentation, the cursor is at the beginning of the line and there are no tabs or spaces even behind the cursor.
If I however delete that newline with backspace and hit return again, the new line is properly indented and the cursor is properly placed at the end of the line.

I don't know where the IDE handles text editing, so I couldn't fix it myself. If you point me in the right direction, maybe I can write a fix.

I'm on x86_64 Linux 4.7.2-1-ARCH with the latest updates installed, in case you don't have this issue and this is specific to my OS/version.

**Comment by eidheim** [comment]
The indentation should work in most "normal" cases. Could you write down an example when it's not working here? And are you using tab or spaces? How many characters in a tab? What file type are you working on?

**Comment by eidheim** [comment]
Oh, and are you editing Windows files? You should copy and paste those, or else gtksourceview might do strange things because of the `\r\n` end line characters in Windows.

**Comment by eidheim** [comment]
If you create Windows files in juCi++ on MSYS2 however, we have normal line endings. But if a project has been created in a different IDE on Windows, it might contain Windows line endings.

**Comment by d3rrial** [comment]
I'm working on linux with files I have created on linux. I might've created some with atom, so let me check if that's the cause.

I've used the standard tab configuration as it comes with juCi++ (2 spaces)
file types I tested this on are .cpp, .cc, .rs

**Comment by eidheim** [comment]
Also please post an minimal example .cpp file where indentation does not work, and where the problem occurs. If the file is created on Linux, then it's not an end line character issue I guess.

**Comment by eidheim** [comment]
You find the indentation functions in source.cc by the way. The on_key_press_event_... functions.

**Comment by d3rrial** [comment]
OK, here is a minimal file where this happens: https://github.com/d3rrial/indentation_error/blob/master/main.cpp
The file was created on Arch with juCi++

The way the problem manifests is like this: You start a new instance of juCi++, go to the end of an indented line and hit return. Then you're in an unindented newline. If that newline is deleted with backspace and return is pressed again, the new line is indented. This only applies to that specific line (at first).
If you set the cursor to the end of another line and do that again, the same occurs again, but if you do this multiple times, the editor seems to catch itself and the newlines are indented correctly from then on.

**Comment by eidheim** [comment]
@zalox Since you're using Arch as well, have you experienced this problem? I can't seem to reproduce this, tried Manjaro.

**Comment by d3rrial** [comment]
This is what it looks like to me: https://www.youtube.com/watch?v=QNOx1PSBtjs

**Comment by eidheim** [comment]
Thank you, let's hope @zalox can reproduce this. If not, I probably have Arch Linux in a container somewhere. One could also have a look at what happens in the Source::View::on_key_press_event_* methods through debugging steps?

**Comment by zalox** [comment]
Not able to reproduce...

**Comment by eidheim** [comment]
@d3rrial Btw, try disable the show_map (set to false) in preferences, and see if that helps.

**Comment by eidheim** [comment]
And are you using Arch in a virtual machine or are you working native on a computer? Or maybe running juCi++ from a difference machine over a network? Just thinking about potential reasons behind the problem.

**Comment by zalox** [comment]
I was able to reproduce once, but it seems to be very inconsistent, at least at my side.

**Comment by eidheim** [comment]
It might be that the source buffer is not updated fast enough when scrolling. I'm thinking disabling show_map might help.

**Comment by d3rrial** [comment]
Yes, disabling the map seems to have solved the issue

**Comment by eidheim** [comment]
Then this is a gtksourceview issue I think, or a gtk issue. Might be that a similar issue has been posten on gtk-, gtksourceview-, gnome-builder- or gedit-bugzilla.

**Comment by d3rrial** [comment]
nvm, I was just able to recreate the problem again, but with map disabled. So that's not the origin I fear

**Comment by eidheim** [comment]
Does it ever happen if you have not scrolled the source in a while?

**Comment by eidheim** [comment]
And are you guys using Wayland by any chance?

**Comment by d3rrial** [comment]
Nah, I'm using X with the i3 window manager on a native arch installation, no VM.

Here's another time where I captured the issue again: https://www.youtube.com/watch?v=W_lYMDxyW4s

**Comment by d3rrial** [comment]
... I think I have the definite reason: I'm daft.

Turns out the numpad return key has a different keyval than the standard return key.

Typical issue between keyboard and chair, it seems?

**Comment by d3rrial** [comment]
I'm facepalming so hard. This is utterly embarrassing...
How did I not notice that I was hitting the numpad return key and the other return key?
Ugh, let me find a hole...

This begs the question tho: Is this behaviour intended or has my idiocy surfaced an actual issue?

**Comment by eidheim** [comment]
Hehe, well either way it should work:) Would you mind posting the keyvals (key->keyval) for both of your return keys? One should be equal to GDK_KEY_Return I take it. Feel free to create a fix PR too by the way, I probably will not work on this until Tomorrow morning, if no PR's has arrived by then:)

**Comment by d3rrial** [comment]
They keyval for my numpad return is: 65421
And the keyval for my normal return is: 65293
