### ISSUE TITLE
Breakpoint Line-Tag (Red Circle)

### ISSUE THREAD

**Issue by d3rrial** [cppit/jucipp#278]
Is it in scope to implement such a marker in juCi++? All the big IDEs I've used before have that (Such as Visual Studio or CLion), the question is if you even want it.

I've done a clumsy example implementation here: https://github.com/d3rrial/jucipp/commit/69f09613c802ee8e44517747a31e0dc3a584d8f9 But that only displays the dot where the git diff tags go, so it doesn't look very pretty:
![breakpoint_dot_cropped](https://cloud.githubusercontent.com/assets/3718129/18224687/afd98d06-71de-11e6-8bed-82bfcdaec1fe.png)

And it also doesn't activate on click, instead just with the normal Ctrl+B breakpoint shortcut.

**Comment by eidheim** [comment]
Are not these marker a remnant from the old days when you did not have the possibility to colour lines? Also use the keyboard instead of the mouse;)

**Comment by d3rrial** [comment]
I don't know. Personally I just like the markers visually.

And I also think it's a waste to have a mouse connected to your PC if you don't use it ;) I always hear about workflow interruptions, but I personally work quite well even with the mouse in my workflow...

As for where it comes from, no idea. I've suggested it because it might be a familiar feature for people who switch from other IDEs to juCi++. Whether it's useful or not, I'm not sure. I personally like being able to click on a line number and have it become a breakpoint and the dot where you clicked is a good visual indication that it actually worked, too.

**Comment by eidheim** [comment]
One possibility could be to add a breakpoint on the line when one clicks on the line number, but without the red circle. You are right, there is the use case when one use the mouse to scroll the source code, and one wants to add a breakpoint without using the keyboard to do so.

**Comment by d3rrial** [comment]
I'm not trying to push for immediate implementation btw. Maybe just put this suggestion somewhere on a "To Consider" list. It's not an important feature after all. Ctrl+B is quick to press and the red line background is a good indicator.

**Comment by eidheim** [comment]
No problem, but I think adding the breakpoint with mouse click is a good solution, if you're interested in looking at the implementation for this. That is, without the red circle:)

**Comment by d3rrial** [comment]
I will look into it. I've not completely understood how the GTK Gutter works, so it'll take a few days or so. If I end up unable to find out how to do it, I'll put another comment on this issue.

**Comment by eidheim** [comment]
Great, thanks alot again!
