### ISSUE TITLE
Make theming possible in juci++

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#28]
I looked into creating dark themes for juCi++, however it seems this has to wait for #14.

**Comment by zalox** [comment]
The gtksourceview (syntax highligting) is defined by xml-files.
The gtk-themes are defined with css-files
The juci-props are defined in json-files
The juci-menu are defined in xml-files

This is messy

**Comment by eidheim** [comment]
My suggestion is to go with the messy way first, then at some point maybe we find a better way to organise this. Though its nice for the user to be able to download gtksourceview highlightings from other sites, as well as gtk-themes maybe. Two files for colors and such is common though, one for theme and one for syntax-highlighting, and then one for other stuff, so its ok I guess.
