### ISSUE TITLE
Autogenerated closing brackets

### ISSUE THREAD

**Issue by d3rrial** [cppit/jucipp#281]
Currently when autocompleting a function/method in juCi++, opening and closing brackets are generated automatically, along with sample content. In other IDEs (Visual Studio / CLion) the automatically generated parentheses are what I'll call unsolid, meaning if `test(/* ... */)` is generated and my cursor is here: `test(/* ... */ꕯ)`, and I hit the closing bracket on my keyboard ")", the new closing bracket I wrote is ignored / replaces the auto-generated bracket, which allows me to then finish the line with ;↵ and be on my merry way with typing in the next line.

In juCi++ however the autogenerated closing bracket is solid, so when my cursor is right before the bracket and I hit a closing bracket, a new closing bracket is generated and I now have two. To get around this I either have to hit the delete key to delete the autogenerated bracket, or never manually close the bracket and skip the created one with the right arrow key, both of which force me to leave the regular working set of keys and enter the numpad area.

I don't know where you handle autogenerated function calls, if you point me in a direction, maybe I can work something out (no promises tho).

I don't know how much this issue affects others, but I personally find it a jarring break in typeflow.

**Comment by eidheim** [comment]
You can probably fix this in `Source::View::on_key_press_event_basic`

**Comment by d3rrial** [comment]
I'll look into it, thanks

**Comment by d3rrial** [comment]
OK, negative from me, I'm unable to figure out. I don't really understand your code well enough to do this.
I'll leave the issue open as a feature request, alright?

**Comment by eidheim** [comment]
Could you write down in pseudocode the wanted behaviour maybe? And which characters should be considered (for instance `)`, `]` and `}`).

**Comment by eidheim** [comment]
I ask mainly in case there are any exceptions to the rule you described above.

**Comment by eidheim** [comment]
One example exception could be if any text is selected.

**Comment by d3rrial** [comment]
Can't write it in pseudocode because I don't know how I would check for bracket-consistency.
What I mean is something like this:

- User accepts auto-complete dialog for a function call
- user inputs function parameters
- when user is before the closing ")" of the generated function call and hits ")" to insert the closing bracket which had already been generated, the input is ignored and the cursor is moved behind the generated ")".

Kinda like this.
I haven't found the autocompletion to be disturbing in any other occurrence.

How do you mean if text is selected?

**Comment by eidheim** [comment]
Ok, I'll think about it. A typical exception to handling keys is when multiple characters are selected in the source view, but I guess we do not need to consider this here, I just used it as an example exception to the rules we need to implement. 

It should be possible to add a Gtk::TextBuffer::Mark at the `)` after doing a completion. You find this completion code in source_clang.cc. And when a `)` is pressed, it is checked if such a mark exists, and if so, move right instead of inserting a `)` (this would happen in `Source::View::on_key_press_event_basic`). The Gtk::TextBuffer::Mark has to be deleted after it is used, or when a new mark is created after a new autocompletion. At least this is my initial thought.

**Comment by d3rrial** [comment]
Well, that makes a lot of sense, could bring another problem with it, tho, for example when a function is generated but the last parameter is the return value of another function
`void test(1,"2",return3f());`
for example

**Comment by eidheim** [comment]
That's a very good example, how is this typically handled? Let's say you replace some value with return3f(), and one other case would be that you write return3f() directly (then you would want the next `)` to be a move instead of an insert. And what if you write a function with parameters inside another function.

**Comment by d3rrial** [comment]
This is getting into the territory of code parsing I think. In other IDEs (VS/CLion (sorry I always compare you to those two, it's not really fair to compare a project like juCi++ to really expensive software)) I can autocomplete the function by tab, input my parameters and also autocomplete new functions inside of the other functions.

When I write  
`void test(1,"2",return3f());`  
and type out the `return3f()`, the brackets appear as they are supposed to, and if I type the bracket for the outter generated function, that bracket is skipped and my cursor is placed ahead.

I believe they achieve this similar to what I've described in my earlier edited comment, by walking through the code and looking checking if all opening brackets have closing brackets. If there is a `(` that has no `)`, then the `)` input is accepted and accepted, but if there is no `(` without a `)` and the cursor is here: `ꕯ)` (ꕯ being the cursor) then the input is rejected and the cursor moved one forward `)ꕯ`. If the user then types the `)` once again, the `)` will get included into the code (because the cursor will only reject a closing bracket if it is itself placed before another closing bracket.)

**Comment by eidheim** [comment]
That should be possible to implement. We already have some functions for finding brackets. I'll look into it later. 

Feel free to compare juCi++ to other IDEs! juCi++ would never have been created if we felt that there already were a great C++ IDE out there, expensive or free.

**Comment by d3rrial** [comment]
Well, I'm pretty sure you aren't able to pay yourselves full-time employment wages from working on juCi++, so that's a reason why I think it's not exactly fair to compare it to projects with enormous budgets (VS) or big budgets (CLion).

I've seen the bracket finding function, but I'm pretty much a C++ beginner and self-taught at that one, so at most I'd be able to generate code that is unworthy of being in your codebase (and probably buggy too). Also I'm super lazy, so... (sorry)

**Comment by eidheim** [comment]
No worries, usually more than one person looks through the PRs. But regarding the bracket finding function(s), I haven't cleaned up that specific code I think (and the naming of those related functions are somewhat horrific), so it's probably not easy to understand. I'll see what I can do to fix this and implement this feature.

**Comment by eidheim** [comment]
@d3rrial Would you mind testing the commit above? I'll do some cleanup before pushing to the cppit/master branch though.

**Comment by d3rrial** [comment]
Sure, will do!

**Comment by d3rrial** [comment]
At first it didn't work, but now it works perfectly for me. I don't know why it didn't work at first, I probably didn't build it properly and after fiddling with the source and rebuilding a few times it started to work...
(even tho the code was ultimately not changed).

The only issue this still has, albeit probably minor, is that the same code also applies to closing brackets that were not auto-generated. I doubt this is much of an issue, as it usually doesn't make sense to write a closing bracket before an opening bracket outside of strings (for which this code doesn't apply). I don't know if this can be fixed with maybe the Gtk::TextBuffer::Mark, but even if it can, it's probably overkill.

I'll do some more extensive testing by applying it on my own codebase and I'll report back in half an hour or so.

**Comment by d3rrial** [comment]
Ugh, I'm bad at finding test cases. It works flawlessly for me. It's slightly strange when I write an if(autogeneratedmethod(), because the closing bracket for the if statement isn't generated automatically, so it creates a visual anomaly even tho it works as intended)

While using this another thing came to mind tho: Maybe extend this to all things that come in pairs?

For example if I write `if(` that the code that turns up in the editor is automagically `if()` while the cursor sits between the parentheses. You already do this (kinda) for the moustaches/curlys.

As far as I know this feature (autogenerating all pair-operators in actual pairs) has mixed popularity so personally I'd implement it, but hide have it disabled by default in the settings.

Examples would be `{}` `[]` `()` `""`
And the same logic could be applied to them (albeit slightly differently for the `""`)

**Comment by eidheim** [comment]
Thank you for the testing and the feedback! I'm busy in the coming days, but will probably cleanup and push the above commit in a few days time. There are some other things I have to improve as well, that is related (mostly old code I want to cleanup).

**Comment by zalox** [comment]
I don't like magic unless J.K. Rowling writes it, so an option to disable magic features would be appreciated.

**Comment by eidheim** [comment]
@zalox that includes the commit above right?

**Comment by zalox** [comment]
@eidheim It hasn't bothered me yet, but I'm struggling with the fact that if you put your cursor like this: `(|)` and write `)`, the action suddenly means `move-cursor-rigth`.  It would most certainly bother me if I was using emacs key bindings.

Also I found this bug:
```c++
auto bracket = std::string('<cursor>); // feature fails if the char is ), not best use case, but I guess you see my bug report
```

**Comment by d3rrial** [comment]
@zalox Typing std::string autogenerates opening and closing brackets for you? It doesn't do that for me... Strange

**Comment by zalox** [comment]
@d3rrial Hi, a better explanation:

```c++
// Given I have this:
auto bracket = std::string();
// Then I type '), and the expected result is:
auto bracket = std::string('));
//' now however, the result is:
auto bracket = std::string(');
//'  now I need to type the ) an extra time to type out
auto bracket = std::string(')');

```

**Comment by d3rrial** [comment]
Yes, you're right, that's a problem.
It could be solved by automatically generating the closing quote together with the opening quote and setting your cursor between them, but that feature has a mixed popularity for good reason.

for example if you have
```cpp
std::string a = "test";
```
And you want to split it up:
```cpp
std::string a = "te"+""st";
```
is what happens.

Preempting user-input is tricky, but can in a lot of cases be quite helpful / time-saving.

**Comment by eidheim** [comment]
I've fixed the problem @zalox reported in https://github.com/eidheim/jucipp/commit/0d5f6f4bc0860ac5940d8c1c3c3ef47cee1614e3. The problem was that a single `'` is not reported as a comment, however, a single `"` for instance is.

**Comment by eidheim** [comment]
@d3rrial I'll consider implementing pair-inserters later, although this will need to be disabled by default like you and @zalox say. We have all the needed functions I think, so it should just be a matter of adding the if-expressions in Source::View::on_key_press_event_bracket_language (I might add this functionallity to all languages, but later).

**Comment by eidheim** [comment]
When I think about it, `Source::View::open_close_bracket_count` needs to be changed slightly to handle `'` and `"`.

**Comment by eidheim** [comment]
Regard in paired insertions as well, See #284
