### ISSUE TITLE
back navigation

### ISSUE THREAD

**Issue by alext234** [cppit/jucipp#292]
- I put cursor at a function call and would like to find out its implementation so i press Ctrl+I
- Once I peek at its implementation I would like to go back to the previous place. How can I do this? Seems there is no shortcut at the moment.

**Comment by eidheim** [comment]
Thank you, this functionality is actually in the works. But since I'm a bit busy at the moment, it will probably take a week or so.

**Comment by eidheim** [comment]
I guess it makes most sense to use alt-arrow left/right for this navigation (like in a web browser).

**Comment by alext234** [comment]
I am fine though I'm little bit used to Vim style, like Ctrl+O.

**Comment by eidheim** [comment]
I'll make it customisable in preferences.

**Comment by zalox** [comment]
In emacs we have for instance `M-d`, or  C-d`. In vim there are similar actions. Most of these `edit-jumps` can be configured through the gtk settings. #163 should be looked into some more I guess. @eidheim Maybe we should provide emacs and vim settings, and a switch in config.json?

**Comment by eidheim** [comment]
@zalox Yeah, someone should look into the NeoVim integration, or at least create a simple example that we could base such an integration on. I do not have the motivation for doing this, especially with lacking documentation on the NeoVim side, but could help complete the integration. Not sure about emacs-mode though, or at least, it seems more people are asking for Vim mode, and we should probably focus on that first. 

This discussion is somewhat unrelated to the feature request though.
