### ISSUE TITLE
Cannot run JuCi on MSYS2 - procedure entry point could not be located.

### ISSUE THREAD

**Issue by Smasherr** [cppit/jucipp#295]
I run MSYS2 on Windows 7 x64 and I managed to build the executable without any issues. But I cant run it after the build:

- If I run it from MSYS2 shell, nothing happens.
- If I run it by double clicking at it in windows explorer, I get the following error message:

![image](https://cloud.githubusercontent.com/assets/10698205/19837115/7883e4d0-9eb3-11e6-9ce8-ffbbc49ba191.png)

which translates to: "The procedure entry point "DllMain" could not be located in the DLL "libgdk_pixbuf-2.0-0.dll"

**Comment by Smasherr** [comment]
I think this should solve it: https://github.com/cppit/jucipp/issues/289

**Comment by Smasherr** [comment]
Since the fix https://github.com/Alexpux/MINGW-packages/pull/1788 has been merged into the master, I assume that updating MSYS2 shoudl solve my problem. I ran

    $ pacman -Sy pacman
    $ pacman -Syu
    $ pacman -Su
    $ pacman -Q mingw-w64-x86_64-gtksourceviewmm3
    mingw-w64-x86_64-gtksourceviewmm3 3.18.0-1

which indicates that I really have the most current version. I ran then

    make clean
    make install

But the issue still remains for me.

**Comment by eidheim** [comment]
For some reason you still have to manually rebuild gtksourceviewmm3. I'm hoping that this package will be rebuilt by msys2 and distributed soon though.

**Comment by Smasherr** [comment]
@eidheim it worked, thanks.
