### ISSUE TITLE
Doesn't recognize .tcc file extension

### ISSUE THREAD

**Issue by sv1990** [cppit/jucipp#304]
Juci doesn't recognize the .tcc which is common for template definition files. 

I couldn't find where to fix it otherwise I would have made this a PR.

**Comment by eidheim** [comment]
Just to be on the safe side, .tcc files can be considered C++ header files right?

If you'd like, you can add an exception inside this scope and create a PR: https://github.com/cppit/jucipp/blob/master/src/source.cc#L38. The correct language id is "cpphdr" I guess. Maybe there are more common extensions for template definition files as well?

**Comment by sv1990** [comment]
I can't think of any other extension. If I simply add
```
else if(file_path.extension().string() == ".tcc")
  language=language_manager->get_language("cpphdr");
```
it only half works. It starts to highlight some of the syntax but then I get the error: "Error: failed to reparse"

**Comment by eidheim** [comment]
Could you try the above commit? It worked on my system.

**Comment by eidheim** [comment]
I'll push the above commit. Let me know if there are any issues.

**Comment by sv1990** [comment]
I don't get that error message but I also don' get full syntax highlighting, e.g. namespaces don't get coloured. 

One other thing that I noticed is that an error marked in my source code that I use an undeclared identifier. This could be due to the fact that .tcc files are included at the and of the corresponding header file and could be a problem of the clang analyzer.

**Comment by eidheim** [comment]
Is the result any different if you rename the .tcc file to .hpp for instance?

**Comment by eidheim** [comment]
Ah, this is how you use it i take it: https://bytes.com/topic/c/answers/138863-what-tcc. Not sure how this should be supported actually. From my understanding, it's a trick for having a separate file for template implementations.

**Comment by sv1990** [comment]
Yes, that's it. 
If it's not possible to support this then it's no problem. I will just put the content of the tcc file back in the header file.
But thanks for trying :)

**Comment by zalox** [comment]
@eidheim could we treat them as .hpp files?

**Comment by zalox** [comment]
Correct me if I'm wrong, but we use gtksourceviewmm for non-state syntax highlighting? We should be able to trick the language detector.

**Comment by danielunderwood** [comment]
Not specifically related to this issue, but would it be worth considering some type of file mapping in the config file? For example, I use some templated files with `.in` extensions that would be nice to be able to configure to some type without it being hardcoded in.

**Comment by eidheim** [comment]
@zalox the .tcc files are special. They are included into a header file to make the header file complete, that is, a .tcc file is not self contained. Look at https://bytes.com/topic/c/answers/138863-what-tcc for a simple example. However, doing this is not something that the is mentioned in https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-source.

@danielunderwood  You can add your own extensions to the files in `/usr/share/gtksourceview-3.0/language-specs/`. If there is some commonly used extension or file type missing, one can also create a PR to the gtksourceview project. On the other hand, I would try follow the Core Guidelines with respect to C++ source file types used in a project if possible.

**Comment by eidheim** [comment]
@zalox I already added the .tcc files as c++ header files: https://github.com/cppit/jucipp/commit/c3f1654b18a83b75ce287b8d70559dc140e2c82a

**Comment by eidheim** [comment]
@danielunderwood I generalised the approach in https://github.com/cppit/jucipp/commit/d038ea93e3b7a63bdcd53f559a8f19353d48b753. You can now add your special template file extensions to `/usr/share/gtksourceview-3.0/language-specs/cpphdr.lang` and they will be parsed as c++ files. 

Note that it is possible to successfully parse the special .tcc files, but it requires to build a complete source file from the header file that includes the .tcc file, and the .tcc file, and pass this to libclang. It requires some work, however, and I will not do this unless such files are mentioned in the Core Guidelines in the future.
