### ISSUE TITLE
Debug deosn't work

### ISSUE THREAD

**Issue by xukai92** [cppit/jucipp#305]
I get this error when trying to do `Start/Continue`:

```
~/temp/test/./build/debug/test returned: -1
```

How to make the debug run?

**Comment by eidheim** [comment]
Try add a breakpoint before your program returns -1.

**Comment by xukai92** [comment]
My program is like this, where my breakpoint is set at the `Hello World!` line.

```cpp
#include <iostream>

int main() {
  std::cout << "Hello World!\n" << std::endl;
  std::cout << "Goodbye World!\n" << std::endl;
  return 0;
}
```

The error in complete is 

```
Compiling and debugging ~/temp/test/./build/debug/test
Scanning dependencies of target test
[ 50%] Building CXX object CMakeFiles/test.dir/main.cpp.o
[100%] Linking CXX executable test
[100%] Built target test
Error (debug): process exited with status -1 (unable to attach)
~/temp/test/./build/debug/test returned: -1
```

**Comment by eidheim** [comment]
What OS are you using? Try google: lldb unable to attach
It might be an OS X issue (if you are using OS X).

**Comment by xukai92** [comment]
Yes I'm running macOS. 

I resolved this by `/usr/sbin/DevToolsSecurity --enable` and restart my machine.

Thanks!
