### ISSUE TITLE
How can I add customised themes to Juci?

### ISSUE THREAD

**Issue by xukai92** [cppit/jucipp#306]
How can I add customised themes to Juci?

**Comment by zalox** [comment]
If you press `Ctrl+,` to open preferences you can set a custom gtk_theme. Read the comment above to see examples. 

There are several providers for gtk-themes and various guides on how to install them, a good starting point to learn more is:

https://wiki.archlinux.org/index.php/GTK%2B#Basic_theme_configuration

**Comment by xukai92** [comment]
Thanks a lot! I'll have a check!
