### ISSUE TITLE
Feature Request: Go to File/Header

### ISSUE THREAD

**Issue by donbcd** [cppit/jucipp#310]
It would be very helpful to be able to have a "go to file" or "go to header" function, which I can use on e.g. includes!

**Comment by adobrich** [comment]
Does the "Go to Declaration" (Ctrl+D) & "Go to Implementation" (Ctrl+I) while cursor is over a function not provide the desired result?

**Comment by eidheim** [comment]
It would be nice if one could go to a header when for instance using go to declaration on the header include, for instance having `#include <vector>` one could use go to declaration on the token `vector`. I'll have a look if this is possible.

**Comment by donbcd** [comment]
It comes handy when you do not have a symbol or you do not know what a specific header provides, and still want to take a look at it. This mainly happens with libraries with deeper nested headers, like boost.

**Comment by eidheim** [comment]
Feel free to try the above commit, I'll probably merge it in a few days.

**Comment by donbcd** [comment]
Just tried it and seems to work fine as long as cmake knows about the headers. This is already a big help!

It stops working when digging deeper, e.g. into the headers of a library (I just tried it with gtkmm: the headers which I use in my project work fine, but the headers included inside these headers work only partially, even though they are in the standard paths).

**Comment by eidheim** [comment]
Thank you, I did fix the include regex, that might have been the problem. Also keep in mind that some includes might depend on `#ifdef` for instance.

**Comment by eidheim** [comment]
@donbcd Yet another regex fix: https://github.com/eidheim/jucipp/commit/f538e22f13e264d5eaf89e9473808d4f4a595780
