### ISSUE TITLE
Feature Request: Jump to project files

### ISSUE THREAD

**Issue by agauniyal** [cppit/jucipp#312]
Eg Ctrl+P in sublime/atom/vscode or any other editor with different keybinding provides an option to quickly jump to another file in the same workspace.

**Comment by eidheim** [comment]
Thank you again, not sure about Ctrl+P though, since it is the default print shortcut, at least for applications that has such an option. Last I checked Atom did not have a print dialog, but juCi++ does, so I think we would need another shortcut for this.

**Comment by junrrein** [comment]
I think printing is not a frequent enough action in IDEs to warrant its own keyboard shortcut.

**Comment by eidheim** [comment]
You might be right that we should remove default the print shortcut. 

Regarding this feature, I think it is not very hard to implement, even for those unfamiliar with the juCi++ code base. I suggest therefore that someone create a PR on this:)

**Comment by zalox** [comment]
@oyvang @tedjk Maybe?

**Comment by Joshua-Wright** [comment]
I believe that my pull request #336 implements a similar functionality, but is missing the Ctrl-P keyboard shortcut. Perhaps we should consider adding that shortcut before merging?

**Comment by eidheim** [comment]
You are right @Joshua-Wright . I'll fix the shortcut when I make corrections to the PR.
