### ISSUE TITLE
windows cmake boost and gtkmm-3.0 error

### ISSUE THREAD

**Issue by Triangle345** [cppit/jucipp#315]
On windows 10, after following the directions on the wiki i recvd this error. Note: I had to use Unix Makefiles and not MSYS Makefiles because MSYS Makefiles did not exist as an option with cmake from msys.

```
$ cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw64 ..                          liblldb not found. Building juCi++ without debugging support
CMake Error: Error in cmake code at
/usr/share/cmake-3.6.2/Modules/FindBoost.cmake:1805:
Parse error.  Function missing ending ")".  End of file reached.
CMake Error at CMakeLists.txt:53 (find_package):
  find_package Error reading CMake code from
  "/usr/share/cmake-3.6.2/Modules/FindBoost.cmake".


-- Checking for module 'gtkmm-3.0'
--   No package 'gtkmm-3.0' found
CMake Error at /usr/share/cmake-3.6.2/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_int       ernal)
  CMakeLists.txt:56 (pkg_check_modules)

```

**Comment by eidheim** [comment]
Try install mingw-w64-x86_64-cmake and run cmake in the MINGW64 shell.

**Comment by Triangle345** [comment]
This seemed to work in installing. Have to remember to open the MSYS64 console though.
However when trying to run juci.exe, getting 

"The procedure entry point: DllMain could not be located in the dynamic link library C:\msys64\mingw64\bin\libgtksourceviewmm-3.0-0.dll"

Do i need to install gtk manually and move the dll's over to msys?

**Comment by eidheim** [comment]
See #289, the solution is to rebuild gtksourceviewmm3. You need to run juci in a MINGW64 shell as well I think.

**Comment by Triangle345** [comment]
So i reinstalled all the packages including gtksourceviewmm but still does not run. In MSYS window it just opens and closes. When running not in MSYS it says the above error.

**Comment by milleniumbug** [comment]
@Triangle345 see [this comment](https://github.com/cppit/jucipp/issues/295#issuecomment-257155491) I had the same issue, and running these commands fixed it

**Comment by Triangle345** [comment]
I see, thank you. Must have missed this while skimming through the issues.
