### ISSUE TITLE
Adding compiler and linker flags

### ISSUE THREAD

**Issue by x64L** [cppit/jucipp#321]
I absolutely love JuCi++, but I've been struggling to add linker and compiler flags.
With Netbeans, for an example, I could add compiler and linker flags under "Additional Options" on my project's properties window.
If, for instance, I were to compile a program which uses the GTK+ library using gcc, I could execute:

> gcc -o output source.c `pkg-config --libs --cflags gtk+-3.0`

Since there are no websites or forums about JuCi++, I thought this would be the perfect place to ask this.
How do I add linker and compiler flags?
Sorry for (probably) such a noob-ish question.

**Comment by milleniumbug** [comment]
juCi++ delegates this responsibility to your build system. Currently CMake and Meson are supported.

**Comment by x64L** [comment]
> juCi++ delegates this responsibility to your build system. Currently CMake and Meson are supported. Dunno about Meson, but CMake allows to call pkg-config directly with pkg_check_modules.
>
I see. Thanks for the quick response!
