### ISSUE TITLE
Feature request: Theming support

### ISSUE THREAD

**Issue by ingmarlehmann** [cppit/jucipp#323]
It would be great to be able to change theme from within the IDE. I see you have screenshots where you are running with different colors than the defaults. Are they hardcoded or is it some sort of gtk thing that I don't know about?

**Comment by eidheim** [comment]
You can change the theme settings in preferences.

**Comment by ingmarlehmann** [comment]
Thank you! I missed that completely even if I was actively looking for it. I run gnome and all menu options besides "About", "Preferences" and "Quit" are within the IDEs UI, whilst the former three are placed in the "top bar special menu".
