### ISSUE TITLE
Feature request: Full screen mode

### ISSUE THREAD

**Issue by ingmarlehmann** [cppit/jucipp#325]
Who doesn't love full screen? Perhaps F11 as a keybinding?

**Comment by eidheim** [comment]
Thank you. Will have to look into if gtk supports this. Feel free to have a look around and potentially create a PR on this though.

**Comment by ingmarlehmann** [comment]
Thanks, never worked with gtk but now might be the time to learn. Will try to find time to get a PR in. Great work btw on this IDE, very impressed so far!

**Comment by ingmarlehmann** [comment]
PR for full screen feature in.

**Comment by eidheim** [comment]
That was fast! I'll have a look Tomorrow morning, I'll probably just make a few minor adjustments.

**Comment by ingmarlehmann** [comment]
Nice, the code was super easy to get into that's why it was so fast.

**Comment by eidheim** [comment]
Fixed in #326
