### ISSUE TITLE
1.2.4 doesn't build [Arch Linux]

### ISSUE THREAD

**Issue by d3rrial** [cppit/jucipp#332]
1.2.4 will not build. I've attached my full build log.

I assume it's because it doesn't build libclangmm first, or something like that.

All dependencies are up to date and I'm on Kernel 4.11.0
[buildlog.txt](https://github.com/cppit/jucipp/files/997236/buildlog.txt)

**Comment by eidheim** [comment]
I think the issue is that you are trying to build latest jucipp without updating the libclangmm submodule. Not sure the git command to do this, but you can do a complete `git clone --recursive https://github.com/cppit/jucipp`.

**Comment by d3rrial** [comment]
Nope, I did a complete recursive clone, I even cloned it again in a different folder.
