### ISSUE TITLE
UTF special characters in sidemap

### ISSUE THREAD

**Issue by d3rrial** [cppit/jucipp#334]
Some special characters are rendered incorrectly, or rather disproportionately large in the sidemap. For example the UTF-8 characters 0x01 or 0x02.
![render_error](https://cloud.githubusercontent.com/assets/3718129/26028476/77c1d89c-3821-11e7-9a8b-76abfdc63402.png)

Nevermind the terrible code for the terribly simple task. I was just really bored today.

**Comment by eidheim** [comment]
Thank you, but the problem lies in gtk+ when its drawing the hexadecimal values of special UTF-8 characters. When the font size becomes small, the square around the hexadecimal values are not correctly adjusted. Please report this issue to gtk+.
