### ISSUE TITLE
pasting removes trailing newlines

### ISSUE THREAD

**Issue by programmerjake** [cppit/jucipp#335]
When I copy and paste a line of code including the newline at the end of the code, pasting removes the last newline. If what I copy has multiple trailing newlines, it keeps all but one of them.

Version 1.2.4
Ubuntu 16.04.2
gcc 5.4.0-6ubuntu1~16.04.4
gtkmm 3.18.0

**Comment by eidheim** [comment]
Thank you for reporting this! Should be fixed in the above commit.

**Comment by programmerjake** [comment]
thanks for fixing quickly!
