### ISSUE TITLE
Cannot select text in code editor

### ISSUE THREAD

**Issue by underdoeg** [cppit/jucipp#337]
I'm on arch linux running gnome shell 3.24. Usually I cannot select text in the code editor. It behaves as if I clicked somwhere else and thus deselect again. Though sometimes it works as expected. This affects selecting by mouse and keyboard as well as the release and git version.

**Comment by eidheim** [comment]
Is this happening in gedit as well? I have not tried 3.24, and am thinking it might be a bug that is recently introduced by gtk+ or gtksourceview.

**Comment by underdoeg** [comment]
no, that was my first thought as well. but gedit and builder are working as expected.

**Comment by eidheim** [comment]
Ok thank you. By the way, is the text deselected when you copy/cut the text, or is it happening while or after selecting the text, that is without any extra actions other than selecting the text?

**Comment by underdoeg** [comment]
It happens while selecting.

But very interesting. I just tried to record a gif to show the bug and now it is gone. Before it kept coming back even after a reboot. I don't know what might have changed... But will report if it should happen again.

**Comment by eidheim** [comment]
I failed to reproduce this behaviour as well. I used Gnome 3.24 on latest Manjaro Gnome. Closing this issue for the time being, but please reopen it if you notice this behaviour repeating.
