### ISSUE TITLE
Can't run in macOS

### ISSUE THREAD

**Issue by thiefuniverse** [cppit/jucipp#338]
Hello,  I have compiled juci in macOS ( which is Sierra 10.12.5). But when I run it, it just aborted.

![image](https://user-images.githubusercontent.com/12184047/27249199-55859caa-5342-11e7-8ff9-32dc331c3dba.png)

I think maybe it's a error from llvm. When I install llvm (4.0.0), it notes that no --with-clang option.

**Comment by eidheim** [comment]
I hope this issue is fixed in the above commit. The reason should be that the latest llvm was not found on MacOS. The `--with-clang` flag seems to be included in llvm by default now, so it is not needed anymore.

**Comment by thiefuniverse** [comment]
Thanks really! I have run it successfully!
