### ISSUE TITLE
Compiled release?

### ISSUE THREAD

**Issue by WharfDarkOne** [cppit/jucipp#345]
I can't seem to be able to compile this  (I'm a complete noob when it comes to this) but I'm looking for a compiled Windows version just to use. If you can upload it here it'd be greatly appreciated.

**Comment by artisdom** [comment]
You need [MSYS2 ](https://msys2.github.io/) to compile and run Juci.
More details here: [Windows with MSYS2](https://github.com/cppit/jucipp/blob/master/docs/install.md#windows-with-msys2-httpsmsys2githubio)

**Comment by chuckysprojects** [comment]
I'm getting multiple errors right now but is there a pre built executable that you can give me?

**Comment by zalox** [comment]
Hi @chuckysprojects, thank you for your interest in this project!
Unfortunately, prebuilt binaries aren't available on any supported platform yet...

If you have specific build issues we would gladly help out if you post your terminal output.

The build is currently [succeeding](https://ci.appveyor.com/project/zalox/jucipp-6hwdu/branch/master) on Windows.

These are the commands that run to update, install dependencies and compile juCi++ on Windows:

```bash
pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade
pacman --noconfirm --sync --refresh --refresh pacman
pacman --noconfirm --sync --refresh --refresh git
export arch=x86_64
pacman -S --noconfirm git mingw-w64-${arch}-cmake make mingw-w64-${arch}-toolchain mingw-w64-${arch}-clang mingw-w64-${arch}-gtkmm3 mingw-w64-${arch}-gtksourceviewmm3 mingw-w64-${arch}-boost mingw-w64-${arch}-aspell mingw-w64-${arch}-aspell-en mingw-w64-${arch}-libgit2
git clone https://github.com/cppit/jucipp
cd jucipp
git submodule update --init --recursive
mkdir -p build
cd build
cmake -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw64 .. #notice the two dots
make
```

**Comment by eidheim** [comment]
After installing MSYS2 and juCi++ it is also important to recompile and reinstall gtksourceviewmm3. Please follow the install instructions, the steps are described there. 

If someone is interested in creating an MSYS2 package for juCi++, feel free to do so, and others can then install this package using pacman in MSYS2. For this to be accepted by the MSYS2 project, it needs to be based on the latest juCi++ release, that is, not a -git package like the one that already exists in MSYS2 ([jucipp-git](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-jucipp-git)). Others have created such packages, for instance for arch linux (in AUR) and FreeBSD.

**Comment by chuckysprojects** [comment]
@eidheim Well after complaining about not having numerous .dll files - this happened. 
![image](https://user-images.githubusercontent.com/27124253/29899561-4d698f20-8e40-11e7-86c5-19b16c70b1c0.png) I guess I'm still not compiling / building it correctly :/

**Comment by eidheim** [comment]
Make sure you run `juci` from the MinGW-w64 shell after installation (assuming you are on 64-bit architecture).

**Comment by eidheim** [comment]
Closing this with the assumption that the issuer made it work.
