### ISSUE TITLE
Home path for windows

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#35]
Boost.Filesystem seems to be missing this function. Does boost::filesystem::path("~/") work under Windows?

**Comment by zalox** [comment]
I solved this, sort of with Singleton::config_dir. We just need to add some preprocessor tags on it and change the getenv(HOME) to getenv(%appdata%/juci), at least for the config files.

**Comment by eidheim** [comment]
Splendid:)

**Comment by zalox** [comment]
To answer your question; boost filesystem does not support ~/. I had to use getenv("home") to get it.
