### ISSUE TITLE
[SOLVED] make error : process.hpp not found

### ISSUE THREAD

**Issue by adithrahman** [cppit/jucipp#351]
jucipp-master/src/terminal.h:11:23: fatal error: process.hpp: No such file or directory
compilation terminated.
src/CMakeFiles/juci.dir/build.make:62: recipe for target 'src/CMakeFiles/juci.dir/config.cc.o' failed
make[2]: *** [src/CMakeFiles/juci.dir/config.cc.o] Error 1
CMakeFiles/Makefile2:157: recipe for target 'src/CMakeFiles/juci.dir/all' failed
make[1]: *** [src/CMakeFiles/juci.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by milleniumbug** [comment]
What is your OS?

**Comment by adithrahman** [comment]
ubuntu 16.04 any solution ?

**Comment by eidheim** [comment]
Did you use —recursive when you cloned this repository?

**Comment by adithrahman** [comment]
ahhh,, i see.. sorry my fault.
SOLVED
