### ISSUE TITLE
yet another one problem with global objects

### ISSUE THREAD

**Issue by uncleyear** [cppit/jucipp#354]
Hi.
There is another problem with global objects(at least one i noticed). With that "old" version of glibmm library(i wonder, it is from april 2017) when we quit, global Project object(Project::current) is destroyed in a time when it is too late to use some resources(again global mutex in glibmm), so quick and easy solutuon would be to assign it a nullptr in an Application' destructor. This happens, for example, when we "compile" project and then exit.

**Comment by eidheim** [comment]
Thank you, should be fixed in the above commit. Pushing to master soon. 

The exit code now also runs when closing a window through the x symbol in its decoration, that is using the desktop environment to close the window.
