### ISSUE TITLE
uninstall target is not defined / clean uninstall instructions needed

### ISSUE THREAD

**Issue by sp-1234** [cppit/jucipp#356]
`make install` installs the project's file(s) globally. It is not very obvious what is the full list of files copied into somewhere in `/usr/local/…` and `make uninstall` is not defined.
Therefore, some clean uninstall instructions are needed.

**Comment by eidheim** [comment]
Sadly CMake does not support this. Please see https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall.
