### ISSUE TITLE
MSYS2: Build instructions need updating

### ISSUE THREAD

**Issue by gitbugged** [cppit/jucipp#372]
I'm sure this is a simple/trivial thing to fix, but it's new to me and I can't figure it out.

Per instructions, we are to install a bunch of packages, but one of them is missing: 

    pacman -S mingw-w64-x86_64-cmake
    error: target not found mingw-w64-x86_64-cmake
    pacman -S cmake
    cmake -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw64 ..
    CMake Error: Could not create named generator MYSYS Makefiles

I can't seem to get past this point.

**Comment by eidheim** [comment]
I think the solution is to use the MinGW-w64 shell, not the MSYS2 shell.

**Comment by gitbugged** [comment]
Where can I find the correct download for MingGW-w64 shell?

Seems that upstream pulled mingw-w64-x86_64-cmake PKGBUILD, as per repo package list: https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/

**Comment by eidheim** [comment]
Please look in the folder where you installed msys2

**Comment by gitbugged** [comment]
That solved the issue, thank you! :+1: 

For reference the correct shell is:

    C:\msys64\mingw64.exe 

The MSYS2 shell was throwing the error for reasons unknown.
