### ISSUE TITLE
`noexcept` not preserved when implementing method

### ISSUE THREAD

**Issue by sv1990** [cppit/jucipp#380]
When I hit `Implement Method` on a method that was declared `noexcept` the proposed function signature misses the `noexcept` keyword which is needed for the code to compile. I don't know if this is a bug in juci or in libclang. 
I have juci from github installed on Manjaro Linux.

**Comment by eidheim** [comment]
Libclang has a isConst function, but no isNoexcept still I think. Let me know if this has changed!

**Comment by sv1990** [comment]
It looks like there is an `isNoexcept` https://clang.llvm.org/doxygen/AnalysisBasedWarnings_8cpp.html#ac6a18f6b7a2e8b4be0620395cd5ed398

**Comment by eidheim** [comment]
Actually, you have clang_getCursorExceptionSpecificationType. I'll see if I can add this to Implement Method soon.

**Comment by eidheim** [comment]
Note that you need llvm/libclang version 5.0 or higher for this support.

**Comment by sv1990** [comment]
Nice. Thanks!
