### ISSUE TITLE
after make install run ldconfig

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#42]
This fixes the "juci: error while loading shared libraries: libclangmm.so: cannot open shared object file: No such file or directory" error when running "juci" without path after "make install". Maybe this should be done from libclangmm's make install when I think about it. Probably some way to do this from CMakeLists.txt (that is, a command for updating the dynamic linker and say there is a new library installed).

**Comment by zalox** [comment]
I think it's automatically done in newer versions of cmake. That's 
probably why it's not working on stable but on testing.

**Comment by eidheim** [comment]
Aha, closing the issue then:)
