### ISSUE TITLE
Downloadable portable

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#49]
I managed to create a moveable working zip. I ran it on Windows Server 2012, Windows 7 and Windows 8.1. With config in appdata. 

I need to figure out gtk warnings or use MS file chooser istead of gnomes.

Footprint is about 60mb.

Edit: Better language.

**Comment by eidheim** [comment]
Nice:)

**Comment by zalox** [comment]
Got footprint down to 47 mb, but zip is 16 mb. Now I will try to use ms explorer instead of gnome to open and save files.

**Comment by eidheim** [comment]
This is great, is the MSYS2 install a prerequisite for your executable?

**Comment by zalox** [comment]
Yes, and the gnome menus work if I copy alot of conf files and link them, but it looks wrong and makes the zip much bigger. Windows open file dialog is already in C:\windows\system32 so no conf should be needed.

**Comment by eidheim** [comment]
Btw do the latest https://github.com/cppit/jucipp compile on Ubuntu 15?

**Comment by eidheim** [comment]
Nvm, I think I got the SIGC_FUNCTORS_DEDUCE_RESULT_TYPE_WITH_DECLTYPE stuff working finally on all platforms. Commit coming soon.

**Comment by zalox** [comment]
I have a working implementation now, however it needs some more work. I need to make it a bit more generic.

**Comment by zalox** [comment]
@eidheim, I can't figure out why this happens:

```sh
[ 80%] Building CXX object src/CMakeFiles/juci.dir/singletons.cc.o
In file included from /home/zalox/projects/juci/src/window.cc:8:0:
/home/zalox/projects/juci/src/dialogs.h:6:22: warning: ‘std::string Dialog::select_folder()’ used but never defined
   static std::string select_folder();
                      ^
/home/zalox/projects/juci/src/dialogs.h:7:22: warning: ‘std::string Dialog::select_file()’ declared ‘static’ but never defined [-Wunused-function]
   static std::string select_file();
                      ^
[ 86%] Building CXX object src/CMakeFiles/juci.dir/cmake.cc.o
[ 93%] Building CXX object src/CMakeFiles/juci.dir/terminal.cc.o
[100%] Building CXX object src/CMakeFiles/juci.dir/dialogs.cc.o
/home/zalox/projects/juci/src/dialogs.cc:5:13: warning: ‘std::string Dialog::select_folder()’ defined but not used [-Wunused-function]
 std::string Dialog::select_folder() {
             ^
In file included from /home/zalox/projects/juci/src/dialogs.cc:1:0:
/home/zalox/projects/juci/src/dialogs.h:7:22: warning: ‘std::string Dialog::select_file()’ declared ‘static’ but never defined [-Wunused-function]
   static std::string select_file();
```

**Comment by zalox** [comment]
Seems like posting this helped me. For some reason I had to use "class" instead of "namespace" to namespace the Dialogs.

**Comment by eidheim** [comment]
Great, since I couldnt figure it out:)

**Comment by zalox** [comment]
Ran into some problems last night.
1. could not compile with mingw64
2. tried to extract the code into a precompiled dll with msvc
3. turns out mingw64 only can communicate with c-code compiled with msvc

Todo:
make c bindings for my windows dialog implementation. I will try to finish this tonight. Have a bit more time this week :)

**Comment by eidheim** [comment]
We could close this, and rather help out and test the various distributed juCi++ packages. I also see no reason to use juCi++ on Windows without MSYS2 with its easily installable open source libraries.
