### ISSUE TITLE
libclang crash on OS X

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#50]
```
Assertion failed: (BeginFileID == EndFileID), function getRawTextSlow, file /tmp/llvm20150821-18657-1xlbfj1/llvm-3.6.2.src/tools/clang/lib/AST/RawCommentList.cpp, line 107.
libclang: crash detected in code completion
Assertion failed: (TemplateIds.empty() && "Still alive TemplateIdAnnotations around?"), function ~Parser, file /tmp/llvm20150821-18657-1xlbfj1/llvm-3.6.2.src/tools/clang/lib/Parse/Parser.cpp, line 417.
```

**Comment by eidheim** [comment]
When doing this in server_ws.hpp at line 72 (eidheim/Simple-WebSocket-Server):
```c++
        class Response {
        public:
            boost::asio::streambuf streambuf;
            std::ostream stream;
            
            Response
        };
```

**Comment by zalox** [comment]
I don't get this behavior on debian testing.

**Comment by eidheim** [comment]
It's on OS X, adding it to title

**Comment by zalox** [comment]
Could it be that libclang selects wrong language type? In ".h-files" for instance it believes it should complete for C or objc?

**Comment by eidheim** [comment]
That is fixed for .h files at least. .hpp should not be a problem.

It is a bug in libclang, at least from what I understand by a couple of google searches. It might be possible to turn off the assertion checks though, but I don't know how yet.

**Comment by eidheim** [comment]
Fixed this in latest libclangmm pull request. At least jucipp do not crash, but the file has to be reloaded to be further parsed by libclang.
