### ISSUE TITLE
Variables within for instance operator[] are not tagged correctly. 

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#52]
https://llvm.org/bugs/show_bug.cgi?id=12972

**Comment by eidheim** [comment]
Maybe use http://clang.llvm.org/doxygen/group__CINDEX__CURSOR__TRAVERSAL.html instead

**Comment by zalox** [comment]
Its that one thats used in the example you gave us in the assignment.

I think you send a pointer to a function call for each  cursor range. It's quite elegant actually.

**Comment by eidheim** [comment]
Ok, I'll fix it next week:)

**Comment by eidheim** [comment]
Do you have a link to that example I gave you?

**Comment by zalox** [comment]
I can't find it anywhere, it was on hpr but I can't find it there anymore. Maybe it's in some email archive or something on your computer from when you wrote the assignment.

**Comment by eidheim** [comment]
Was this the one:
http://www.ics.com/blog/introduction-clang-part-2
?

**Comment by zalox** [comment]
Yes.

**Comment by eidheim** [comment]
Fixed in latest libclangmm pull request

**Comment by eidheim** [comment]
Btw, the http://www.ics.com/blog/introduction-clang-part-2 way to do it did not work. Did not get the correct range for variables declared, for instance:
```c++
size_t c;
```
Here the range got from 0 to the end of c for some reason.

**Comment by zalox** [comment]
Aha, I gave up finding a solution for this earlier this year.
