### ISSUE TITLE
Debugger integration through lldb library

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#53]
I would really like to see a feature in the future where we can toggle breakpoints in the code to debug better.

Here is some information how to use gdb
[https://www.cs.cmu.edu/~gilpin/tutorial/](https://www.cs.cmu.edu/~gilpin/tutorial/)

**Comment by eidheim** [comment]
LLDB might be the way to go? I'm not sure, but it might have some kind of integration possibilities with our current libclang code. Also, best case, is that we use its library instead of the runnable, which most likely is more clean that the gdb one. I don't know debuggers though, never use them unless to figure out a segmentation fault.

**Comment by eidheim** [comment]
I'll soon be working on this.

**Comment by eidheim** [comment]
I think I go for lldb direct integration, that is using the lldb library. Debian and OS X at least have distributed packages for this, although a bit unsure if MSYS2 will get one. lldb is currently commented out in https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-clang/PKGBUILD#L14, but I guess that will be solved some time in the future. 

The lldb library will be a hassle to install on OS X through `brew install --with-clang --with-lldb llvm` though: https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt

**Comment by eidheim** [comment]
First screenshot of meaningful debug info through the lldb library:
![screen shot 2015-12-27 at 17 17 40](https://cloud.githubusercontent.com/assets/5269318/12011018/266a1a12-acbe-11e5-833f-345d972fabe5.png)

**Comment by eidheim** [comment]
The lldb library is pretty good, if one overlooks complete lack of documentation and being a nightmare to setup on OS X (have not tried other platforms yet). My only worry is MSYS2 at the moment. 

@mingwandroid do you think lldb will be installable through MSYS2 in the near future? I noticed lldb was commented out here https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-clang/PKGBUILD#L14. Could only find this old issue from 2014 on it: https://github.com/Alexpux/MINGW-packages/issues/168

**Comment by mingwandroid** [comment]
@eidheim We can give it a go: https://gist.github.com/mingwandroid/ddeca4ffe5cb7a215461

Totally untested. I tend to do any new development work in the -git versions (it's called clang-svn but it's really clang-git) when possible since it has a higher chance of working (esp. for something like this) and if I need to develop new patches (or backport any) to the non-git version at the endi, it's very easy with git.

**Comment by eidheim** [comment]
Great, I'll try it out Tomorrow, thank you again.

**Comment by mingwandroid** [comment]
LLDB (in 3.7.0 and probably latest svn) is not yet ready for Windows (at least MinGW-w64).

I ran into a few problems:
Various (probably related) C string formatting errors (PRIu64 -> warning: unknown conversion type character 'l' in format) .. functions not decorated with gnu_print attribute?
LLDB 'host' header clashes with 'build' headers: lldb/include/lldb/Host/windows/win32.h:14 mingw64/x86_64-w64-mingw32/include/sys/timeb.h:90:8: error: previous definition of 'struct timespec'
 struct timespec {

.. I'll try some more later.

**Comment by eidheim** [comment]
Getting closer to some basic debugger functionality; start, stop, continue, toggle breakpoint (just some minor work before I create a debugger_integration branch):

![screen shot 2015-12-28 at 18 44 32](https://cloud.githubusercontent.com/assets/5269318/12022789/8007a578-ad93-11e5-8c7f-4bc46301f468.png)

**Comment by mingwandroid** [comment]
on Windows?

**Comment by eidheim** [comment]
Oh, sorry, only tested it on OS X.

**Comment by mingwandroid** [comment]
Heh, no problem (I should've guessed from the look of it actually) .. I was just being hopeful that you found time to investigate. I'm having to look into some problems with on MSYS2 with Python2/GEGL/gobject-introspection today.

**Comment by eidheim** [comment]
Sorry, no, got caught up in working on the lldb integration. Will try to have a look at the MSYS2 clang-svn  package in the following days, although I probably have to go through all the other diffs to try to understand it all, might take some time before I can do something constructive there!

**Comment by mingwandroid** [comment]
Don't worry, I will get round to it in a few days and in-fact have more progress than the gist already.

I'm also considering looking into adding gnome-builder to MSYS2, which is, I guess a bit of a "cousin-project" to this one? But first of all, we need to upgrade GIMP which means upgrading GEGL which means figuring out what's up with Python2, which means making it debuggable again (like it used to be, I'm sure of it)

**Comment by eidheim** [comment]
Gnome-builder is an interesting project, and luckily it ensures continued effort into gtksourceview and libgit2-glib. Hopefully they will find some of the things we have done useful too.

**Comment by mingwandroid** [comment]
I'm sure they will!

**Comment by eidheim** [comment]
Now shows debug status and line where the debug process is currently stopped:

![screen shot 2015-12-29 at 12 36 39](https://cloud.githubusercontent.com/assets/5269318/12033882/2c4030c2-ae29-11e5-98cd-d71da6727cae.png)

However, is all very thread unsafe yet (have focused on the functionality first). I'll fix that Tomorrow and hopefully create the debug_integration branch then. After that it should not take long to add steps for instance. Please let me know what debug functionality you guys can't live without.

**Comment by mingwandroid** [comment]
Early console support means you give users access to all features at a pinch, then can figure out which to IDEize at a more leisurely pace!

For me, clickable call stacks with as much argument context as possible would be next after that.

**Comment by zalox** [comment]
Awesome work! I've got some functionality I'd like to see:

* Run line by line
* Follow function call
* Track variables

**Comment by eidheim** [comment]
I'll prioritise the console support as suggested by @mingwandroid , that is before steps for instance. Only thing that needs to be changed and updated on the visual side would be the breakpoint locations if they are changed in the debug console, the rest should work automatically. 
Guess I have to create an extra tab in the terminal window (bottom window) for the debug console. Need a couple more days for this:)

**Comment by eidheim** [comment]
See #153
