### ISSUE TITLE
Right click menu in folder three

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#6]
Create a right click menu in the folder three.

The menu should at least contain:
* Delete

edit: updated

**Comment by eidheim** [comment]
Folder tree is currently being refreshed using Directories::open_folder when needed. Although at some point I'll move the cursor (in directories) to the file that is opened in current tab if it has the same project_path.

**Comment by eidheim** [comment]
Folder tree selection of shown tab-file and refresh (if opening the same folder) is working now in the latest commit.

**Comment by eidheim** [comment]
Working on this now. Moving files/folders in directory view using drag and drop is done. Soon finished with the right click functions.

**Comment by eidheim** [comment]
See https://github.com/eidheim/jucipp/commit/2f705d2ee76fba32b05708ceadbf3aefb078815a. Not sure why reference to this commit did not show in this issue.
