### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#60]
After working in juci for about an hour it uses about 5GB ram with one file open.

**Comment by eidheim** [comment]
What approximately did you do in that hour? Opening/closing several files, or working on one file mostly?

**Comment by zalox** [comment]
I guess the terminal buffer can get quite big, other than that normal coding. I only had one file open. dialog_win.cc on my github.

**Comment by eidheim** [comment]
Indeed, do you think that was the problem? I know I had trouble with too large terminal buffer when printing out in infinite loops for instance. Going to clean up terminal at some point, and can add max lines in terminal-buffer then.
