### ISSUE TITLE
Chaotic times: new gtk3, clang and g++ versions

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#62]
At the moment gnome3.18 is coming and most distributors are working hard to create binaries of gtk3.18 packages with their dependencies and related sources. Expect some issues until this is all worked out. Homebrew will soon, for instance, ship with gtksourceviewmm3.18, they have already shipped gtksourceview3.18, and at the moment there are some incompabilities with current gtksourceviewmm. Have also convinced MSYS2 to ship with gtksourceviewmm, but they will ship 3.18, and not versions below. I guess we have to wait some hours/days here as well. 

Also, newest version of clang (3.7) has some issues, but 3.6 and below should work fine. 

On top of this, I think Debian is on its way to compile all their packages with gcc5.2, which could lead to additional strangeness in the near future, at least for those using Debian testing/unstable/experimental directly or indirectly through child distributions. 

Edit: The MSYS 2 contributors seems to be working quite effectively:)

**Comment by eidheim** [comment]
The msys2 author has already added the new version of gtksourceview3 AND gtksourceviewmm3. Impressive! Have not tested it yet though.

**Comment by zalox** [comment]
Sweet! Does this mean we don't need to compile it our self before install?

**Comment by eidheim** [comment]
In theory, yes!

**Comment by eidheim** [comment]
By the way, gtksourceview 3.18 has sourcemap as well. Going to add this for users having this version, when the sourceview version issues on OS X is fixed.

**Comment by eidheim** [comment]
![image](https://cloud.githubusercontent.com/assets/5269318/10097633/93bb6414-637a-11e5-9194-b8ad47745869.png)

Sourcemap implemented if you have gtk* versions 3.18:) No idea why the selected field is gray though. Might be better on Linux where one has OpenGL support.

**Comment by zalox** [comment]
Great work! That combined with "jump to method" gives great overviews!

I think we should start thinking about adding a "view" option in the menu. Personally I have disabled all GUI elements in emacs except for the editing window.

**Comment by eidheim** [comment]
Closing this, as the issues are mostly fixed in the latest pull request.
