### ISSUE TITLE
git support through libgit2

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#63]
~~libgit2 is somewhat ugly, hopefully https://github.com/GNOME/libgit2-glib is better. libgit2-glib(-dev) is installable through distribution-included packages in Debian, OS X, and MSYS2.~~

**Comment by zalox** [comment]
It looks like it would be a good idea to wrap parts of this library for c++ if we are going to use it.

**Comment by eidheim** [comment]
Yeah, haven't looked at the library yet, but a git.h and git.cc should be sufficient. It should support functions for directory and source (creating a subclass of Gsv::View between Gsv::View and Source::View).
At first:
* directory showing deleted, added and modified files using colors
* Source showing added, modified and deleted lines in Gsv::Gutter (using custom Gsv::Marks I guess), much like Atom does it

**Comment by eidheim** [comment]
I am currently testing libgit2 here: https://github.com/eidheim/libgit2-test. The library is really nice to work with so I guess I'll add this to juCi++ in a month or so.

**Comment by eidheim** [comment]
See #244
