### ISSUE TITLE
juci gets clang errors when wrong ending on line

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#71]
I was programming now and got an diagnostic message saying "Error: no constructor definition for Directories"

in notebook.cc on line ~185
```c++
  // Where directories was underlined with error. 
  auto directories = *Singleton::directories();
  if(directories.cmake && directories.cmake->pr//.......
```

I put the cursor at the end of the line and pressed delete until I got this:
```c++
  auto directories = *Singleton::directories();if(directories.cmake && directories.cmake->pr//.......
```
I pressed enter and got back to the first snippet, then the error message disappeared. I also tried to repoen juci, but no luck, only by deleting the line change character and replacing it I got rid of the message.

**Comment by zalox** [comment]
This was on debian stable.

**Comment by eidheim** [comment]
Weird that you managed to remove the error message, anyway, it should be there and the issue is fixed. I did not manage to get rid of the error message btw on either OS X or debian testing.

**Comment by eidheim** [comment]
The trick was to write `auto directories = Singleton::directories();` and then just click Apply Fix-Its;)

**Comment by zalox** [comment]
No, this was not the issue. I'm aware of this. Juci made different diagnostics depending on line-ending.

**Comment by eidheim** [comment]
Ok, I'll check on debian stable

**Comment by eidheim** [comment]
Debian stable still runs libclang 3.5, so I think the problem lies there. I was unable to get an error on the line with `auto directories = *Singleton::directories();` using libclang 3.5

**Comment by zalox** [comment]
I quess this issue is related to #77. Closing it for the time being.
