### ISSUE TITLE
Boost version 1.59 preperation

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#74]
Changes to boost that affects this project:
* Property Tree:
```sh
A new JSON parser with full Unicode support.
Breaking change: The new parser does not support comments or string concatenation in JSON files. These features were non-standard extensions of the old parser but their removal could break code which was relying on them.
```
We need to document the config file due to this.

Also boost log breaks: 
* Boost log
```sh
Breaking change: The library has been ported to Boost.TypeIndex for its underlying type info management tool. This affected the following public interfaces:
invalid_type exceptions thrown by the library now have typeindex::type_index attached as the description of the offending type. The type was previously identified by type_info_wrapper.
Boost.Exception type_info_info error information now contains typeindex::type_index instead of type_info_wrapper.
attribute_value::get_type() now returns typeindex::type_index instead of type_info_wrapper. User-defined attribute value implementations should be similarly changed (the attribute_value::impl::get_type() virtual method now also returns typeindex::type_index).
```
I do not think we break because of this, but nice to keep in mind.

**Comment by eidheim** [comment]
I'm changing .config then to the following, for instance:
{
    "version": "0.9.4",
    "default_window_size": {
        "width": 600,
        "height": 400
    },
    "terminal_history_size": 1000,
    "gtk_theme": {
        "name_comment": "Use \"\" for default theme, At least these two exist on all systems: Adwaita, Raleigh",
        "name": "Adwaita",
        "variant_comment": "Use \"\" for default variant, and \"dark\" for dark theme variant",
        "variant": ""
    },
...

What do you think? One could later add tooltips etc, but the simplest solutions are often best.
