### ISSUE TITLE
Error in pasting into a file

### ISSUE THREAD

**Issue by Redlab1** [cppit/jucipp#77]
Hello!

Whenever I'm trying to copy and paste from a text editor into a file in juci, I get this crash and error:

"(juci:5780): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtktextbtree.c:4020: byte index off the end of the line

(juci:5780): Gtk-ERROR **: Byte index 2 is off the end of the line".

**Comment by eidheim** [comment]
Is this with the latest version of juci (see #51)? If so, what OS do you use?

**Comment by zalox** [comment]
I'd like to see the log file (~/.juci/log/juci.log) and your "cmake ."-output aswell.

**Comment by Redlab1** [comment]
Yes. I just git pulled the latest version. I'm on linux debian 8.2.

**Comment by Redlab1** [comment]
"cmake ."-output: 
"-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   thread
--   log
--   system
--   filesystem
-- Configuring done
-- Generating done
-- Build files have been written to: /home/balder/jucipp."

logfile (Cant upload it, due to write permission):
** Info: /home/balder/jucipp/src/juci.cc@init_logging(11): "Logging initalized"
** Debug: /home/balder/jucipp/src/window.cc@Window(26): "start"
** Debug: /home/balder/jucipp/src/directories.cc@Directories(25): "start"
** Debug: /home/balder/jucipp/src/directories.cc@update(148): "start"
** Debug: /home/balder/jucipp/src/directories.cc@update(154): "end"
** Debug: /home/balder/jucipp/src/window.cc@Window(125): "end"
** Debug: /home/balder/jucipp/src/directories.cc@open(122): "start"
** Debug: /home/balder/jucipp/src/directories.cc@open(144): "end"
** Debug: /home/balder/jucipp/src/notebook.cc@open(58): "start"
** Debug: /home/balder/jucipp/src/source_clang.cc@ClangViewParse(25): "start"
** Debug: /home/balder/jucipp/src/source_clang.cc@ClangViewParse(75): "end"
** Debug: /home/balder/jucipp/src/directories.cc@select(158): "start"
** Debug: /home/balder/jucipp/src/directories.cc@select(198): "end"
** Debug: /home/balder/jucipp/src/notebook.cc@open(147): "end"
** Debug: /home/balder/jucipp/src/directories.cc@update(148): "start"
** Debug: /home/balder/jucipp/src/directories.cc@update(154): "end"
** Debug: /home/balder/jucipp/src/notebook.cc@open(58): "start"
** Debug: /home/balder/jucipp/src/source_clang.cc@ClangViewParse(25): "start"
** Debug: /home/balder/jucipp/src/source_clang.cc@ClangViewParse(75): "end"
** Debug: /home/balder/jucipp/src/directories.cc@select(158): "start"
** Debug: /home/balder/jucipp/src/directories.cc@select(198): "end"
** Debug: /home/balder/jucipp/src/notebook.cc@open(147): "end"

**Comment by eidheim** [comment]
It would be great if you could create a minimal test case where juci fails, that is copied text that crashes juci when pasted.

**Comment by Redlab1** [comment]
So, what I'm doing when it's crashing is:
1. Make a new project.
2. Make a new file.
3. Copy text into the file.

The text I'm trying to paste into the file is: 
http://pastebin.com/taGuWaAV

This is by the way your file eidheim :)

**Comment by eidheim** [comment]
Ah yeah, I might fix this on Monday or so. It's a Windows-file, which probably contains non-utf8 characters. Think I have to replace the non-utf8 chars before pasting. Thank you for reporting the issue:)

**Comment by eidheim** [comment]
A temporary fix is to open it in juci directly, instead of pasting it. Then the non-standard chars gets removed automatically.

**Comment by Redlab1** [comment]
I tried to do this. But the files doesnt seem to recognize each other, because I get a lot of undefined references out of this. But thank you for your time!

**Comment by eidheim** [comment]
Undefined references sounds like a different problem. Remember to add all your .cpp-files in add_executable in the CMakeLists.txt. For instance:
```cmake
add_executable(oving1 main.cpp broek.cpp)
```
