### ISSUE TITLE
Are open pipes cleared and correctly closed when quiting juci?

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#79]
I quit juci during in app compilation on windows. I found the cplusplus process working some time after shutdown "~1 min".

**Comment by eidheim** [comment]
pipes are, but libclang may continue to work. There is no way to force libclang to stop as far as I know.

**Comment by eidheim** [comment]
Or, when I think about it, Windows processes are abit strange, there might be a pipe or something I do not close in terminal_win.cc, but most likely its a Windows issue. 

Did you run alot of run commands? Did they all return?

**Comment by eidheim** [comment]
When I think some more about it, there is an issue on Windows when killing processes, this is done when juci quits, but Windows may or may not do this. Its a Windows issue, not a jucipp one.

**Comment by eidheim** [comment]
How did you quit juci btw? Destroying it in terminal might have a different outcome than clicking control-q or clicking on the exit button on the window.

**Comment by zalox** [comment]
I quit using the menu, Juci++/quit.

**Comment by eidheim** [comment]
Tried killing compilation on Windows, and that didn't work. It's a Windows issue.

**Comment by eidheim** [comment]
It did get killed after a while though.
