### ISSUE TITLE
Crashes when directories becomes empty after applying exceptions in config

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#82]
How to recreate:
* Add "" as exception making all files to be ignored by the directory list.

**Comment by eidheim** [comment]
The directoryfilter is complicating the code, and fixing this issue will complicate the code even further. My proposal is to remove this option altogether, as it is not very, if at all, important.

**Comment by eidheim** [comment]
Yes I tried to fix it, but the issue together with caching of the directory structure made it very hard.
