### ISSUE TITLE
Juci needs to ask "are you sure you want to close?"

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#83]
I have deleted work.

**Comment by eidheim** [comment]
Is the dialog "Do you want to save..." not enough? Or did it not appear when you had unsaved work?

**Comment by zalox** [comment]
I guess it's enough. I just got very frustrated last night. (there are limits to how much struggle one can take from python bindings) I'll unbind the quit key-binding my settings to solve this issue.
