### ISSUE TITLE
readability issues?

### ISSUE THREAD

**Issue by VadimGit** [cppit/jucipp#90]
Cursorily looking through the code:
no coments?
messy with gtkmm class names?
no "final", "override", "default" ext. keywords to simplify readability.
inheritance vs composition, especially from stl )))
and more others.
Feel like project will become unmaintainable after a while.
I am not an expert in c++ and can be wrong. It's all IMHO.

**Comment by eidheim** [comment]
Compared to what this project does, it is pretty clean. The above issues are minor, but needs to be addressed at some point.

**Comment by eidheim** [comment]
Keep in mind that we have not announced this project yet, but there are two cleanups that are a priority of mine in the following couple of weeks:
* Make platform independent process class (remove duplicate code from terminal*), and in addition publish this as a separate library
* Simplify autocomplete code, and make it general so it can be reused by Python plugins

**Comment by VadimGit** [comment]
Then sorry about that. 
I'd make cmake parser as a libryary too. In the furure guys from cmake will make something like "cmake-metadata-generator" or even "wathcer" or "server-mode" to simplify working with ide:
http://article.gmane.org/gmane.comp.programming.tools.cmake.devel/13004/match=cmake+metadata

Regarding code. ""messy with gtkmm class names?"" I meant something like this:
```c++
class Notebook : public Gtk::Notebook {
public:
  Notebook();
```

**Comment by eidheim** [comment]
When creating libraries, namespaces are a must, but inside an application project like this I feel it just leads to more code, as long as one never writes `using namespace Gtk` that is. More of a personal preference really, no namespace: this application, but it would be harder to identify local classes from included classes, I see that, so maybe we should reconsider this. We do not use many local classes declared in the cc-files though. 

I found this though in src/directories.h after reading your comments:
```c++
class Directories : public Gtk::ScrolledWindow {
```
which should rather be:
```c++
class Directories : public Gtk::TreeView {
```
And thus it would be easier to modify from Python plugins for instance.

**Comment by eidheim** [comment]
Regarding a cmake library, it would be really helpful if the guys from CMake made this. Would love to scrap this part away from juCi++. Half a year ago I could not find any libraries for cmake, and thus we created the CMake class.

**Comment by VadimGit** [comment]
```c++
class Notebook : public Gtk::Notebook {
public:
  Notebook();
```
In this case I meant under the hood we have the "base class constructor with same name" not a simple method besides the type with same name. If it would a simple method it would be a simple overriding but it's a constructor.Technically it works (I was not looking in ISO about that) but it's hard to read, hard to debug, hard to do refactoring. 

I'd renamed it like:
```c++
class JucippNotebook : public Gtk::Notebook {
public:
  JucippNotebook();
```

**Comment by eidheim** [comment]
I would prefer juci::Notebook, but within the juci namespace the class declaration code would be the same. Much like std::thread and boost::thread.

**Comment by VadimGit** [comment]
**Make platform independent process class (remove duplicate code from terminal*), and in addition publish this as a separate library**

Did you consider using libuv instead of boost collection, especially if you want to publish platform as a library. I think It could be much easier to implement platform and language independent api with libuv?

**Comment by eidheim** [comment]
libuv is a C library, and as boost is c++, well designed, stable, and used in most c++ projects, boost is a better choice in my opinion. Boost also has a high number of available packages, more than libuv.

**Comment by eidheim** [comment]
But I did not know about libuv, it was a very interesting project. Thank you for making me aware of this library.

**Comment by VadimGit** [comment]
libuv is an asynchronous c library but very well designed, well documented, has minimum dependencies, very fast and robust. It's a basement for nodejs bat also a lot of new projects choose libuv: https://github.com/libuv/libuv/wiki/Projects-that-use-libuv
for this project boost looks like overkill (dependency, compile time), especially if you are planning to separate platform as a library. libuv looks like it's designed for projects like this.  file system watcher out of the box for example, can be very useful for any IDE. IMHO. 

Node.js itself is written in c++.

**Comment by eidheim** [comment]
Using modern C++ libraries when you have good alternatives should be prioritised to keep the number of source code lines to a minimum. This is cleaner, leads to fewer bugs, higher readability, and is well worth the increase in compile time and more complex dependencies. Besides, the compile time is mainly affected by the gtkmm headers.

**Comment by eidheim** [comment]
I take the liberty to close this issue, as the code base has improved both by your commits, and other cleanup commits.
