### ISSUE TITLE
Changing CMakeLists.txt when having many files open

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#92]
If I have many files open my computer melts because of async reparse of all the files at once.

Options:
1. Queue the reparse
2. Reparse only visible file, and others when changed to

**Comment by zalox** [comment]
Juci also reparses files that are not affected by the CMakeLists change. I.E. files that belong to a different project.

**Comment by eidheim** [comment]
Queue the reparse and reparse files when changed to is a good idea, like when .h files are saved. I thought I fixed the second issue, that only project files were reparsed, but will have another look at it.

**Comment by zalox** [comment]
Maybe it's just my branch. I'll try to merge in master before I continue.

**Comment by eidheim** [comment]
I tested the second issue, and it should work. If not, check the project paths and see it they are set correctly.
